// Copyright (C) 2025 Cromwell D. Enage

#include <odds_and_ends/static_introspection/concept/is_value_generator.hpp>
#include <boost/random/linear_congruential.hpp>
#include <boost/random/additive_combine.hpp>
#include <boost/random/shuffle_order.hpp>
#include <boost/random/taus88.hpp>
#include <boost/random/inversive_congruential.hpp>
#include <boost/random/mersenne_twister.hpp>
#include <boost/random/lagged_fibonacci.hpp>
#include <boost/random/ranlux.hpp>
#include <boost/random/splitmix64.hpp>
#include <boost/random/xoshiro.hpp>
#include <boost/core/lightweight_test.hpp>

int main(int argc, char** argv)
{
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::minstd_rand0
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::minstd_rand
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::rand48
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::ecuyer1988
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::kreutzer1986
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::knuth_b
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::taus88
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::hellekalek1995
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::mt11213b
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::mt19937
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::mt19937_64
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::lagged_fibonacci607
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::lagged_fibonacci1279
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::lagged_fibonacci2281
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::lagged_fibonacci3217
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::lagged_fibonacci4423
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::lagged_fibonacci9689
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::lagged_fibonacci19937
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::lagged_fibonacci23209
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::lagged_fibonacci44497
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::ranlux3
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::ranlux4
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::ranlux3_01
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::ranlux4_01
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::ranlux64_3_01
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::ranlux64_4_01
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::splitmix64
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::xoshiro128f
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::xoshiro128mm
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::xoshiro128pp
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::xoshiro256d
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::xoshiro256mm
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::xoshiro256pp
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::xoshiro512d
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::xoshiro512mm
        >::value
    );
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_value_generator<
            ::boost::random::xoshiro512pp
        >::value
    );
    return ::boost::report_errors();
}
