// Copyright (C) 2025-2026 Cromwell D. Enage

#include <string>
#include <odds_and_ends/node/container/list.hpp>
#include <odds_and_ends/static_introspection/concept/is_reversible_container.hpp>
#include <boost/core/lightweight_test.hpp>

typedef ::odds_and_ends::node::container::list<char> CharList;

void test_char_list_00()
{
    static_assert(
        ::odds_and_ends::static_introspection::concept
        ::is_reversible_container<CharList,::boost::mpl::integral_c<unsigned int,4> >::value,
        "::odds_and_ends::node::container::list is a C++-Standard Reversible Container."
    );

    CharList char_list;
    CharList::const_iterator c_itr = char_list.begin();
    CharList::const_reverse_iterator c_r_itr = char_list.rbegin();

    BOOST_TEST(char_list.empty());
    BOOST_TEST(c_itr == char_list.end());
    BOOST_TEST(c_r_itr == char_list.rend());
    char_list.push_back('m');
    c_itr = char_list.begin();
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    char_list.push_back('n');
    c_itr = char_list.begin();
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    char_list.push_back('o');
    c_itr = char_list.begin();
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    char_list.push_front('l');
    c_itr = char_list.begin();
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    char_list.push_front('k');
    c_itr = char_list.begin();
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    char_list.push_back('q');
    c_itr = char_list.begin();
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    c_itr = char_list.end();

    CharList::iterator itr = char_list.insert(--c_itr, 'p');

    BOOST_TEST('p' == *itr);
    c_itr = char_list.begin();
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    char_list.push_front('h');
    c_itr = char_list.begin();
    BOOST_TEST('h' == *c_itr);
    ++c_itr;
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('h' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    c_itr = char_list.begin();
    itr = char_list.insert(++c_itr, 'i');
    BOOST_TEST('i' == *itr);
    c_itr = char_list.begin();
    BOOST_TEST('h' == *c_itr);
    ++c_itr;
    BOOST_TEST('i' == *c_itr);
    ++c_itr;
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('i' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('h' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    char_list.push_front('a');
    c_itr = char_list.begin();
    BOOST_TEST('a' == *c_itr);
    ++c_itr;
    BOOST_TEST('h' == *c_itr);
    ++c_itr;
    BOOST_TEST('i' == *c_itr);
    ++c_itr;
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('i' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('h' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('a' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());

    ::std::string sample = "bcdefg";

    c_itr = char_list.begin();
    itr = char_list.insert(++c_itr, sample.cbegin(), sample.cend());
    BOOST_TEST('b' == *itr);
    c_itr = char_list.begin();
    BOOST_TEST('a' == *c_itr);
    ++c_itr;
    BOOST_TEST('b' == *c_itr);
    ++c_itr;
    BOOST_TEST('c' == *c_itr);
    ++c_itr;
    BOOST_TEST('d' == *c_itr);
    ++c_itr;
    BOOST_TEST('e' == *c_itr);
    ++c_itr;
    BOOST_TEST('f' == *c_itr);
    ++c_itr;
    BOOST_TEST('g' == *c_itr);
    ++c_itr;
    BOOST_TEST('h' == *c_itr);
    ++c_itr;
    BOOST_TEST('i' == *c_itr);
    ++c_itr;
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('i' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('h' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('g' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('f' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('e' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('d' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('c' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('b' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('a' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    c_itr = char_list.begin();
    ++c_itr;
    ++c_itr;
    ++c_itr;
    ++c_itr;
    itr = char_list.erase(c_itr);
    BOOST_TEST('f' == *itr);
    c_itr = char_list.begin();
    BOOST_TEST('a' == *c_itr);
    ++c_itr;
    BOOST_TEST('b' == *c_itr);
    ++c_itr;
    BOOST_TEST('c' == *c_itr);
    ++c_itr;
    BOOST_TEST('d' == *c_itr);
    ++c_itr;
    BOOST_TEST('f' == *c_itr);
    ++c_itr;
    BOOST_TEST('g' == *c_itr);
    ++c_itr;
    BOOST_TEST('h' == *c_itr);
    ++c_itr;
    BOOST_TEST('i' == *c_itr);
    ++c_itr;
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('i' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('h' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('g' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('f' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('d' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('c' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('b' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('a' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());

    CharList::iterator itr_last = char_list.end();

    --itr_last;
    itr = --itr_last;
    --itr;
    --itr;
    --itr;
    itr = char_list.erase(itr, itr_last);
    BOOST_TEST('p' == *itr);
    c_itr = char_list.begin();
    BOOST_TEST('a' == *c_itr);
    ++c_itr;
    BOOST_TEST('b' == *c_itr);
    ++c_itr;
    BOOST_TEST('c' == *c_itr);
    ++c_itr;
    BOOST_TEST('d' == *c_itr);
    ++c_itr;
    BOOST_TEST('f' == *c_itr);
    ++c_itr;
    BOOST_TEST('g' == *c_itr);
    ++c_itr;
    BOOST_TEST('h' == *c_itr);
    ++c_itr;
    BOOST_TEST('i' == *c_itr);
    ++c_itr;
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_list.end());
    c_r_itr = char_list.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('i' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('h' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('g' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('f' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('d' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('c' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('b' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('a' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_list.rend());
    char_list.clear();
    BOOST_TEST(char_list.empty());
}

int main(int argc, char** argv)
{
    test_char_list_00();
    return ::boost::report_errors();
}

