// Copyright (C) 2025 Cromwell D. Enage

#include <string>
#include <odds_and_ends/node/container/deque.hpp>
#include <odds_and_ends/node/balancer/left_leaning_red_black_tree.hpp>
#include <odds_and_ends/node/red_black.hpp>
#include <odds_and_ends/static_introspection/concept/is_container.hpp>
#include <boost/mpl/deque.hpp>
#include <boost/core/lightweight_test.hpp>

typedef ::odds_and_ends::node::container::deque<
    char,
    ::boost::mpl::deque< ::odds_and_ends::node::red_black>,
    ::odds_and_ends::node::left_leaning_red_black_tree_balancer
> CharDeque;

void test_char_deque_00()
{
/*
    static_assert(
        ::odds_and_ends::static_introspection::concept::is_container<CharDeque>::value,
        ""
    );
*/
    CharDeque char_deque;
    CharDeque::const_iterator c_itr = char_deque.begin();
    CharDeque::const_reverse_iterator c_r_itr = char_deque.rbegin();

    BOOST_TEST(char_deque.empty());
    BOOST_TEST(c_itr == char_deque.end());
    BOOST_TEST(c_r_itr == char_deque.rend());
    char_deque.push_back('m');
    BOOST_TEST('m' == char_deque[0]);
    c_itr = char_deque.begin();
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());
    char_deque.push_back('n');
    BOOST_TEST('m' == char_deque[0]);
    BOOST_TEST('n' == char_deque[1]);
    c_itr = char_deque.begin();
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());
    char_deque.push_back('o');
    BOOST_TEST('m' == char_deque[0]);
    BOOST_TEST('n' == char_deque[1]);
    BOOST_TEST('o' == char_deque[2]);
    c_itr = char_deque.begin();
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());
    char_deque.push_front('l');
    BOOST_TEST('l' == char_deque[0]);
    BOOST_TEST('m' == char_deque[1]);
    BOOST_TEST('n' == char_deque[2]);
    BOOST_TEST('o' == char_deque[3]);
    c_itr = char_deque.begin();
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());
    char_deque.push_front('k');
    BOOST_TEST('k' == char_deque[0]);
    BOOST_TEST('l' == char_deque[1]);
    BOOST_TEST('m' == char_deque[2]);
    BOOST_TEST('n' == char_deque[3]);
    BOOST_TEST('o' == char_deque[4]);
    c_itr = char_deque.begin();
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());
    char_deque.push_back('q');
    BOOST_TEST('k' == char_deque[0]);
    BOOST_TEST('l' == char_deque[1]);
    BOOST_TEST('m' == char_deque[2]);
    BOOST_TEST('n' == char_deque[3]);
    BOOST_TEST('o' == char_deque[4]);
    BOOST_TEST('q' == char_deque[5]);
    c_itr = char_deque.begin();
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());
    c_itr = char_deque.begin();
    c_itr += 5;

    CharDeque::iterator itr = char_deque.insert(c_itr, 'p');

    BOOST_TEST('k' == char_deque[0]);
    BOOST_TEST('l' == char_deque[1]);
    BOOST_TEST('m' == char_deque[2]);
    BOOST_TEST('n' == char_deque[3]);
    BOOST_TEST('o' == char_deque[4]);
    BOOST_TEST('p' == char_deque[5]);
    BOOST_TEST('q' == char_deque[6]);
    BOOST_TEST('p' == *itr);
    c_itr = char_deque.begin();
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());
    char_deque.push_front('h');
    BOOST_TEST('h' == char_deque[0]);
    BOOST_TEST('k' == char_deque[1]);
    BOOST_TEST('l' == char_deque[2]);
    BOOST_TEST('m' == char_deque[3]);
    BOOST_TEST('n' == char_deque[4]);
    BOOST_TEST('o' == char_deque[5]);
    BOOST_TEST('p' == char_deque[6]);
    BOOST_TEST('q' == char_deque[7]);
    c_itr = char_deque.begin();
    BOOST_TEST('h' == *c_itr);
    ++c_itr;
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('h' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());
    c_itr = char_deque.begin();
    ++c_itr;
    itr = char_deque.insert(c_itr, 'i');
    BOOST_TEST('h' == char_deque[0]);
    BOOST_TEST('i' == char_deque[1]);
    BOOST_TEST('k' == char_deque[2]);
    BOOST_TEST('l' == char_deque[3]);
    BOOST_TEST('m' == char_deque[4]);
    BOOST_TEST('n' == char_deque[5]);
    BOOST_TEST('o' == char_deque[6]);
    BOOST_TEST('p' == char_deque[7]);
    BOOST_TEST('q' == char_deque[8]);
    BOOST_TEST('i' == *itr);
    c_itr = char_deque.begin();
    BOOST_TEST('h' == *c_itr);
    ++c_itr;
    BOOST_TEST('i' == *c_itr);
    ++c_itr;
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('i' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('h' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());
    char_deque.push_front('a');
    BOOST_TEST('a' == char_deque[0]);
    BOOST_TEST('h' == char_deque[1]);
    BOOST_TEST('i' == char_deque[2]);
    BOOST_TEST('k' == char_deque[3]);
    BOOST_TEST('l' == char_deque[4]);
    BOOST_TEST('m' == char_deque[5]);
    BOOST_TEST('n' == char_deque[6]);
    BOOST_TEST('o' == char_deque[7]);
    BOOST_TEST('p' == char_deque[8]);
    BOOST_TEST('q' == char_deque[9]);
    c_itr = char_deque.begin();
    BOOST_TEST('a' == *c_itr);
    ++c_itr;
    BOOST_TEST('h' == *c_itr);
    ++c_itr;
    BOOST_TEST('i' == *c_itr);
    ++c_itr;
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('i' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('h' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('a' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());

    ::std::string sample = "bcdefg";

    c_itr = char_deque.begin();
    itr = char_deque.insert(++c_itr, sample.cbegin(), sample.cend());
    BOOST_TEST('a' == char_deque[0]);
    BOOST_TEST('b' == char_deque[1]);
    BOOST_TEST('c' == char_deque[2]);
    BOOST_TEST('d' == char_deque[3]);
    BOOST_TEST('e' == char_deque[4]);
    BOOST_TEST('f' == char_deque[5]);
    BOOST_TEST('g' == char_deque[6]);
    BOOST_TEST('h' == char_deque[7]);
    BOOST_TEST('i' == char_deque[8]);
    BOOST_TEST('k' == char_deque[9]);
    BOOST_TEST('l' == char_deque[10]);
    BOOST_TEST('m' == char_deque[11]);
    BOOST_TEST('n' == char_deque[12]);
    BOOST_TEST('o' == char_deque[13]);
    BOOST_TEST('p' == char_deque[14]);
    BOOST_TEST('q' == char_deque[15]);
    BOOST_TEST('b' == *itr);
    c_itr = char_deque.begin();
    BOOST_TEST('a' == *c_itr);
    ++c_itr;
    BOOST_TEST('b' == *c_itr);
    ++c_itr;
    BOOST_TEST('c' == *c_itr);
    ++c_itr;
    BOOST_TEST('d' == *c_itr);
    ++c_itr;
    BOOST_TEST('e' == *c_itr);
    ++c_itr;
    BOOST_TEST('f' == *c_itr);
    ++c_itr;
    BOOST_TEST('g' == *c_itr);
    ++c_itr;
    BOOST_TEST('h' == *c_itr);
    ++c_itr;
    BOOST_TEST('i' == *c_itr);
    ++c_itr;
    BOOST_TEST('k' == *c_itr);
    ++c_itr;
    BOOST_TEST('l' == *c_itr);
    ++c_itr;
    BOOST_TEST('m' == *c_itr);
    ++c_itr;
    BOOST_TEST('n' == *c_itr);
    ++c_itr;
    BOOST_TEST('o' == *c_itr);
    ++c_itr;
    BOOST_TEST('p' == *c_itr);
    ++c_itr;
    BOOST_TEST('q' == *c_itr);
    ++c_itr;
    BOOST_TEST(c_itr == char_deque.end());
    c_r_itr = char_deque.rbegin();
    BOOST_TEST('q' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('p' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('o' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('n' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('m' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('l' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('k' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('i' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('h' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('g' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('f' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('e' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('d' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('c' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('b' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST('a' == *c_r_itr);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == char_deque.rend());
    char_deque.clear();
    BOOST_TEST(char_deque.empty());
}

int main(int argc, char** argv)
{
    test_char_deque_00();
    return ::boost::report_errors();
}

