// Copyright (C) 2026 Cromwell D. Enage

#include <odds_and_ends/node/container/trie_map.hpp>

typedef ::odds_and_ends::node::container::trie_map<char,unsigned int> TrieMap;

#include <algorithm>
#include <boost/range/begin.hpp>
#include <boost/range/end.hpp>

bool your_str_equal(char const* lhs, TrieMap::key_type const& rhs)
{
    return ::std::equal(::boost::begin(rhs), ::boost::end(rhs), lhs);
}

#include <boost/core/lightweight_test.hpp>

void test_00()
{
    TrieMap trie_map;
    TrieMap::const_iterator c_itr = trie_map.cbegin();

    BOOST_TEST(c_itr == trie_map.cend());

    TrieMap::const_reverse_iterator c_r_itr = trie_map.crbegin();

    BOOST_TEST(c_r_itr == trie_map.crend());

    TrieMap::iterator itr = trie_map.emplace("in", 1);

    BOOST_TEST(your_str_equal("in", itr->first));
    BOOST_TEST(1 == itr->second);
    c_itr = trie_map.find("i");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("in");
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
    itr = trie_map.emplace("inn", 3);
    BOOST_TEST(your_str_equal("inn", itr->first));
    BOOST_TEST(3 == itr->second);
    c_itr = trie_map.find("i");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("inn");
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("inn", c_r_itr->first));
    BOOST_TEST(3 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
    itr = trie_map.emplace("ink", 2);
    BOOST_TEST(your_str_equal("ink", itr->first));
    BOOST_TEST(2 == itr->second);
    c_itr = trie_map.find("i");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("ink");
    BOOST_TEST(your_str_equal("ink", c_itr->first));
    BOOST_TEST(2 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ink", c_itr->first));
    BOOST_TEST(2 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("inn", c_r_itr->first));
    BOOST_TEST(3 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ink", c_r_itr->first));
    BOOST_TEST(2 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
    itr = trie_map.emplace("to", 10);
    BOOST_TEST(your_str_equal("to", itr->first));
    BOOST_TEST(10 == itr->second);
    c_itr = trie_map.find("t");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("to");
    BOOST_TEST(your_str_equal("to", c_itr->first));
    BOOST_TEST(10 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ink", c_itr->first));
    BOOST_TEST(2 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("to", c_itr->first));
    BOOST_TEST(10 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("to", c_r_itr->first));
    BOOST_TEST(10 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("inn", c_r_itr->first));
    BOOST_TEST(3 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ink", c_r_itr->first));
    BOOST_TEST(2 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
    itr = trie_map.emplace("ten", 9);
    BOOST_TEST(your_str_equal("ten", itr->first));
    BOOST_TEST(9 == itr->second);
    c_itr = trie_map.find("t");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("te");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("ten");
    BOOST_TEST(your_str_equal("ten", c_itr->first));
    BOOST_TEST(9 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ink", c_itr->first));
    BOOST_TEST(2 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ten", c_itr->first));
    BOOST_TEST(9 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("to", c_itr->first));
    BOOST_TEST(10 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("to", c_r_itr->first));
    BOOST_TEST(10 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ten", c_r_itr->first));
    BOOST_TEST(9 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("inn", c_r_itr->first));
    BOOST_TEST(3 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ink", c_r_itr->first));
    BOOST_TEST(2 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
    itr = trie_map.emplace("ted", 8);
    BOOST_TEST(your_str_equal("ted", itr->first));
    BOOST_TEST(8 == itr->second);
    c_itr = trie_map.find("t");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("te");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("ted");
    BOOST_TEST(your_str_equal("ted", c_itr->first));
    BOOST_TEST(8 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ink", c_itr->first));
    BOOST_TEST(2 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ted", c_itr->first));
    BOOST_TEST(8 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ten", c_itr->first));
    BOOST_TEST(9 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("to", c_itr->first));
    BOOST_TEST(10 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("to", c_r_itr->first));
    BOOST_TEST(10 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ten", c_r_itr->first));
    BOOST_TEST(9 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ted", c_r_itr->first));
    BOOST_TEST(8 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("inn", c_r_itr->first));
    BOOST_TEST(3 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ink", c_r_itr->first));
    BOOST_TEST(2 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
    itr = trie_map.emplace("tear", 7);
    BOOST_TEST(your_str_equal("tear", itr->first));
    BOOST_TEST(7 == itr->second);
    c_itr = trie_map.find("t");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("te");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("tea");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("tear");
    BOOST_TEST(your_str_equal("tear", c_itr->first));
    BOOST_TEST(7 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ink", c_itr->first));
    BOOST_TEST(2 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("tear", c_itr->first));
    BOOST_TEST(7 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ted", c_itr->first));
    BOOST_TEST(8 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ten", c_itr->first));
    BOOST_TEST(9 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("to", c_itr->first));
    BOOST_TEST(10 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("to", c_r_itr->first));
    BOOST_TEST(10 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ten", c_r_itr->first));
    BOOST_TEST(9 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ted", c_r_itr->first));
    BOOST_TEST(8 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("tear", c_r_itr->first));
    BOOST_TEST(7 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("inn", c_r_itr->first));
    BOOST_TEST(3 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ink", c_r_itr->first));
    BOOST_TEST(2 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
    itr = trie_map.emplace("team", 6);
    BOOST_TEST(your_str_equal("team", itr->first));
    BOOST_TEST(6 == itr->second);
    c_itr = trie_map.find("t");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("te");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("tea");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("team");
    BOOST_TEST(your_str_equal("team", c_itr->first));
    BOOST_TEST(6 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ink", c_itr->first));
    BOOST_TEST(2 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("team", c_itr->first));
    BOOST_TEST(6 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("tear", c_itr->first));
    BOOST_TEST(7 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ted", c_itr->first));
    BOOST_TEST(8 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ten", c_itr->first));
    BOOST_TEST(9 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("to", c_itr->first));
    BOOST_TEST(10 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("to", c_r_itr->first));
    BOOST_TEST(10 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ten", c_r_itr->first));
    BOOST_TEST(9 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ted", c_r_itr->first));
    BOOST_TEST(8 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("tear", c_r_itr->first));
    BOOST_TEST(7 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("team", c_r_itr->first));
    BOOST_TEST(6 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("inn", c_r_itr->first));
    BOOST_TEST(3 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ink", c_r_itr->first));
    BOOST_TEST(2 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
    itr = trie_map.emplace("teal", 5);
    BOOST_TEST(your_str_equal("teal", itr->first));
    BOOST_TEST(5 == itr->second);
    c_itr = trie_map.find("t");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("te");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("tea");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("teal");
    BOOST_TEST(your_str_equal("teal", c_itr->first));
    BOOST_TEST(5 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ink", c_itr->first));
    BOOST_TEST(2 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("teal", c_itr->first));
    BOOST_TEST(5 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("team", c_itr->first));
    BOOST_TEST(6 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("tear", c_itr->first));
    BOOST_TEST(7 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ted", c_itr->first));
    BOOST_TEST(8 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ten", c_itr->first));
    BOOST_TEST(9 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("to", c_itr->first));
    BOOST_TEST(10 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("to", c_r_itr->first));
    BOOST_TEST(10 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ten", c_r_itr->first));
    BOOST_TEST(9 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ted", c_r_itr->first));
    BOOST_TEST(8 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("tear", c_r_itr->first));
    BOOST_TEST(7 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("team", c_r_itr->first));
    BOOST_TEST(6 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("teal", c_r_itr->first));
    BOOST_TEST(5 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("inn", c_r_itr->first));
    BOOST_TEST(3 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ink", c_r_itr->first));
    BOOST_TEST(2 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
    itr = trie_map.emplace("tea", 4);
    BOOST_TEST(your_str_equal("tea", itr->first));
    BOOST_TEST(4 == itr->second);
    c_itr = trie_map.find("t");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("te");
    BOOST_TEST(c_itr == trie_map.cend());
    c_itr = trie_map.find("tea");
    BOOST_TEST(your_str_equal("tea", c_itr->first));
    BOOST_TEST(4 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ink", c_itr->first));
    BOOST_TEST(2 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("tea", c_itr->first));
    BOOST_TEST(4 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("teal", c_itr->first));
    BOOST_TEST(5 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("team", c_itr->first));
    BOOST_TEST(6 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("tear", c_itr->first));
    BOOST_TEST(7 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ted", c_itr->first));
    BOOST_TEST(8 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ten", c_itr->first));
    BOOST_TEST(9 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("to", c_itr->first));
    BOOST_TEST(10 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("to", c_r_itr->first));
    BOOST_TEST(10 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ten", c_r_itr->first));
    BOOST_TEST(9 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ted", c_r_itr->first));
    BOOST_TEST(8 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("tear", c_r_itr->first));
    BOOST_TEST(7 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("team", c_r_itr->first));
    BOOST_TEST(6 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("teal", c_r_itr->first));
    BOOST_TEST(5 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("tea", c_r_itr->first));
    BOOST_TEST(4 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("inn", c_r_itr->first));
    BOOST_TEST(3 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ink", c_r_itr->first));
    BOOST_TEST(2 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
    itr = trie_map.emplace("A", 0);
    BOOST_TEST(your_str_equal("A", itr->first));
    BOOST_TEST(0 == itr->second);
    c_itr = trie_map.find("A");
    BOOST_TEST(your_str_equal("A", c_itr->first));
    BOOST_TEST(0 == c_itr->second);
    c_itr = trie_map.cbegin();
    BOOST_TEST(your_str_equal("A", c_itr->first));
    BOOST_TEST(0 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("in", c_itr->first));
    BOOST_TEST(1 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ink", c_itr->first));
    BOOST_TEST(2 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("inn", c_itr->first));
    BOOST_TEST(3 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("tea", c_itr->first));
    BOOST_TEST(4 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("teal", c_itr->first));
    BOOST_TEST(5 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("team", c_itr->first));
    BOOST_TEST(6 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("tear", c_itr->first));
    BOOST_TEST(7 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ted", c_itr->first));
    BOOST_TEST(8 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("ten", c_itr->first));
    BOOST_TEST(9 == c_itr->second);
    ++c_itr;
    BOOST_TEST(your_str_equal("to", c_itr->first));
    BOOST_TEST(10 == c_itr->second);
    ++c_itr;
    BOOST_TEST(c_itr == trie_map.cend());
    c_r_itr = trie_map.crbegin();
    BOOST_TEST(your_str_equal("to", c_r_itr->first));
    BOOST_TEST(10 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ten", c_r_itr->first));
    BOOST_TEST(9 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ted", c_r_itr->first));
    BOOST_TEST(8 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("tear", c_r_itr->first));
    BOOST_TEST(7 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("team", c_r_itr->first));
    BOOST_TEST(6 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("teal", c_r_itr->first));
    BOOST_TEST(5 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("tea", c_r_itr->first));
    BOOST_TEST(4 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("inn", c_r_itr->first));
    BOOST_TEST(3 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("ink", c_r_itr->first));
    BOOST_TEST(2 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("in", c_r_itr->first));
    BOOST_TEST(1 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(your_str_equal("A", c_r_itr->first));
    BOOST_TEST(0 == c_r_itr->second);
    ++c_r_itr;
    BOOST_TEST(c_r_itr == trie_map.crend());
}

int main(int argc, char** argv)
{
    test_00();
    return ::boost::report_errors();
}

