// Copyright (C) 2025 Cromwell D. Enage

#include <odds_and_ends/node/data.hpp>
#include <odds_and_ends/node/tree/base.hpp>
#include <odds_and_ends/node/tree/binary.hpp>
#include <odds_and_ends/node/iterator/breadth_first_tree.hpp>
#include <odds_and_ends/node/iterator/in_order_tree.hpp>
#include <odds_and_ends/composite_type/composite_type.hpp>
#include <boost/mpl/deque.hpp>
#include <boost/core/lightweight_test.hpp>

typedef ::odds_and_ends::composite_type::composite_type<
    ::boost::mpl::deque<
        ::odds_and_ends::node::data<int>,
        ::odds_and_ends::node::tree::base<>,
        ::odds_and_ends::node::tree::binary<>
    >
> binary_tree_node;

void test_00()
{
    binary_tree_node n09(9);
    binary_tree_node n17(17);
    binary_tree_node n23(23);
    binary_tree_node n50(50);
    binary_tree_node n76(76);

    BOOST_TEST(9 == *n09);
    BOOST_TEST(17 == *n17);
    BOOST_TEST(23 == *n23);
    BOOST_TEST(50 == *n50);
    BOOST_TEST(76 == *n76);
    n50.set_left(n17);
    n50.set_right(n76);
    n17.set_left(n09);
    n17.set_right(n23);
    BOOST_TEST(!n50.parent());
    BOOST_TEST(50 == **n17.parent());
    BOOST_TEST(17 == **n50.left());
    BOOST_TEST(50 == **n76.parent());
    BOOST_TEST(76 == **n50.right());
    BOOST_TEST(17 == **n09.parent());
    BOOST_TEST(9 == **n17.left());
    BOOST_TEST(17 == **n23.parent());
    BOOST_TEST(23 == **n17.right());
    BOOST_TEST(!n09.left());
    BOOST_TEST(!n09.right());
    BOOST_TEST(!n23.left());
    BOOST_TEST(!n23.right());
    BOOST_TEST(!n76.left());
    BOOST_TEST(!n76.right());

    ::odds_and_ends::node::in_order_tree_iterator<binary_tree_node> in_ord_fwd_itr(n50);

    BOOST_TEST(9 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(9 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(23 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(23 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(50 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(23 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(50 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(76 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(50 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(76 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(76 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);

    ::odds_and_ends::node::in_order_tree_iterator<
        binary_tree_node,
        ::boost::mpl::true_
    > in_ord_rev_itr(n50);

    BOOST_TEST(76 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(50 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(76 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(50 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(23 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(50 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(23 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(23 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(9 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(9 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(9 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);

    binary_tree_node::traits::pointer rotate_result = n50.rotate_right();

    BOOST_TEST(17 == **rotate_result);
    BOOST_TEST(!n17.parent());
    BOOST_TEST(17 == **n09.parent());
    BOOST_TEST(9 == **n17.left());
    BOOST_TEST(17 == **n50.parent());
    BOOST_TEST(50 == **n17.right());
    BOOST_TEST(50 == **n23.parent());
    BOOST_TEST(23 == **n50.left());
    BOOST_TEST(50 == **n76.parent());
    BOOST_TEST(76 == **n50.right());
    BOOST_TEST(!n09.left());
    BOOST_TEST(!n09.right());
    BOOST_TEST(!n23.left());
    BOOST_TEST(!n23.right());
    BOOST_TEST(!n76.left());
    BOOST_TEST(!n76.right());
    in_ord_fwd_itr = ::odds_and_ends::node::make_in_order_tree_iterator(n17);
    BOOST_TEST(9 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(9 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(23 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(23 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(50 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(23 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(50 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(76 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(50 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(76 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(76 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    in_ord_rev_itr = ::odds_and_ends::node::make_in_order_tree_reverse_iterator(n17);
    BOOST_TEST(76 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(50 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(76 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(50 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(23 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(50 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(23 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(23 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(9 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(9 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(9 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    rotate_result = n17.rotate_left();
    BOOST_TEST(50 == **rotate_result);
    BOOST_TEST(!n50.parent());
    BOOST_TEST(50 == **n17.parent());
    BOOST_TEST(17 == **n50.left());
    BOOST_TEST(50 == **n76.parent());
    BOOST_TEST(76 == **n50.right());
    BOOST_TEST(17 == **n09.parent());
    BOOST_TEST(9 == **n17.left());
    BOOST_TEST(17 == **n23.parent());
    BOOST_TEST(23 == **n17.right());
    BOOST_TEST(!n09.left());
    BOOST_TEST(!n09.right());
    BOOST_TEST(!n23.left());
    BOOST_TEST(!n23.right());
    BOOST_TEST(!n76.left());
    BOOST_TEST(!n76.right());
    in_ord_fwd_itr = ::odds_and_ends::node::make_in_order_tree_iterator(n50);
    BOOST_TEST(9 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(9 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(23 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(23 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(50 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(23 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(50 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(76 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(50 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(76 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(76 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    in_ord_rev_itr = ::odds_and_ends::node::make_in_order_tree_reverse_iterator(n50);
    BOOST_TEST(76 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(50 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(76 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(50 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(23 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(50 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(23 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(23 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(9 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(9 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(9 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
}

void test_01()
{
    binary_tree_node n01(1);
    binary_tree_node n06(6);
    binary_tree_node n08(8);
    binary_tree_node n11(11);
    binary_tree_node n13(13);
    binary_tree_node n15(15);
    binary_tree_node n17(17);
    binary_tree_node n22(22);
    binary_tree_node n25(25);
    binary_tree_node n27(27);

    BOOST_TEST(1 == *n01);
    BOOST_TEST(!n01.parent());
    BOOST_TEST(!n01.left());
    BOOST_TEST(!n01.right());
    BOOST_TEST(n01.begin() == n01.end());
    BOOST_TEST(n01.rbegin() == n01.rend());
    BOOST_TEST(6 == *n06);
    BOOST_TEST(!n06.parent());
    BOOST_TEST(!n06.left());
    BOOST_TEST(!n06.right());
    BOOST_TEST(n06.begin() == n06.end());
    BOOST_TEST(n06.rbegin() == n06.rend());
    BOOST_TEST(8 == *n08);
    BOOST_TEST(!n08.parent());
    BOOST_TEST(!n08.left());
    BOOST_TEST(!n08.right());
    BOOST_TEST(n08.begin() == n08.end());
    BOOST_TEST(n08.rbegin() == n08.rend());
    BOOST_TEST(11 == *n11);
    BOOST_TEST(!n11.parent());
    BOOST_TEST(!n11.left());
    BOOST_TEST(!n11.right());
    BOOST_TEST(n11.begin() == n11.end());
    BOOST_TEST(n11.rbegin() == n11.rend());
    BOOST_TEST(13 == *n13);
    BOOST_TEST(!n13.parent());
    BOOST_TEST(!n13.left());
    BOOST_TEST(!n13.right());
    BOOST_TEST(n13.begin() == n13.end());
    BOOST_TEST(n13.rbegin() == n13.rend());
    BOOST_TEST(15 == *n15);
    BOOST_TEST(!n15.parent());
    BOOST_TEST(!n15.left());
    BOOST_TEST(!n15.right());
    BOOST_TEST(n15.begin() == n15.end());
    BOOST_TEST(n15.rbegin() == n15.rend());
    BOOST_TEST(17 == *n17);
    BOOST_TEST(!n17.parent());
    BOOST_TEST(!n17.left());
    BOOST_TEST(!n17.right());
    BOOST_TEST(n17.begin() == n17.end());
    BOOST_TEST(n17.rbegin() == n17.rend());
    BOOST_TEST(22 == *n22);
    BOOST_TEST(!n22.parent());
    BOOST_TEST(!n22.left());
    BOOST_TEST(!n22.right());
    BOOST_TEST(n22.begin() == n22.end());
    BOOST_TEST(n22.rbegin() == n22.rend());
    BOOST_TEST(25 == *n25);
    BOOST_TEST(!n25.parent());
    BOOST_TEST(!n25.left());
    BOOST_TEST(!n25.right());
    BOOST_TEST(n25.begin() == n25.end());
    BOOST_TEST(n25.rbegin() == n25.rend());
    BOOST_TEST(27 == *n27);
    BOOST_TEST(!n27.parent());
    BOOST_TEST(!n27.left());
    BOOST_TEST(!n27.right());
    BOOST_TEST(n27.begin() == n27.end());
    BOOST_TEST(n27.rbegin() == n27.rend());
    n06.set_left(n01);
    BOOST_TEST(6 == **n01.parent());
    BOOST_TEST(1 == **n06.left());
    BOOST_TEST(1 == **n06.begin());
    BOOST_TEST(n06.begin() + 1 == n06.end());
    BOOST_TEST(1 == **n06.rbegin());
    BOOST_TEST(n06.rbegin() + 1 == n06.rend());
    n08.set_left(n06);
    BOOST_TEST(8 == **n06.parent());
    BOOST_TEST(6 == **n08.left());
    BOOST_TEST(6 == **n08.begin());
    BOOST_TEST(n08.begin() + 1 == n08.end());
    BOOST_TEST(6 == **n08.rbegin());
    BOOST_TEST(n08.rbegin() + 1 == n08.rend());
    n08.set_right(n11);
    BOOST_TEST(8 == **n11.parent());
    BOOST_TEST(11 == **n08.right());
    BOOST_TEST(6 == **n08.begin());
    BOOST_TEST(11 == **(n08.begin() + 1));
    BOOST_TEST(n08.begin() + 2 == n08.end());
    BOOST_TEST(11 == **n08.rbegin());
    BOOST_TEST(6 == **(n08.rbegin() + 1));
    BOOST_TEST(n08.rbegin() + 2 == n08.rend());
    n13.set_left(n08);
    BOOST_TEST(13 == **n08.parent());
    BOOST_TEST(8 == **n13.left());
    BOOST_TEST(8 == **n13.begin());
    BOOST_TEST(n13.begin() + 1 == n13.end());
    BOOST_TEST(8 == **n13.rbegin());
    BOOST_TEST(n13.rbegin() + 1 == n13.rend());
    n13.set_right(n17);
    BOOST_TEST(13 == **n17.parent());
    BOOST_TEST(17 == **n13.right());
    BOOST_TEST(8 == **n13.begin());
    BOOST_TEST(17 == **(n13.begin() + 1));
    BOOST_TEST(n13.begin() + 2 == n13.end());
    BOOST_TEST(17 == **n13.rbegin());
    BOOST_TEST(8 == **(n13.rbegin() + 1));
    BOOST_TEST(n13.rbegin() + 2 == n13.rend());
    n17.set_left(n15);
    BOOST_TEST(17 == **n15.parent());
    BOOST_TEST(15 == **n17.left());
    BOOST_TEST(15 == **n17.begin());
    BOOST_TEST(n17.begin() + 1 == n17.end());
    BOOST_TEST(15 == **n17.rbegin());
    BOOST_TEST(n17.rbegin() + 1 == n17.rend());
    n17.set_right(n25);
    BOOST_TEST(17 == **n25.parent());
    BOOST_TEST(25 == **n17.right());
    BOOST_TEST(15 == **n17.begin());
    BOOST_TEST(25 == **(n17.begin() + 1));
    BOOST_TEST(n17.begin() + 2 == n17.end());
    BOOST_TEST(25 == **n17.rbegin());
    BOOST_TEST(15 == **(n17.rbegin() + 1));
    BOOST_TEST(n17.rbegin() + 2 == n17.rend());
    n25.set_left(n22);
    BOOST_TEST(25 == **n22.parent());
    BOOST_TEST(22 == **n25.left());
    BOOST_TEST(22 == **n25.begin());
    BOOST_TEST(n25.begin() + 1 == n25.end());
    n25.set_right(n27);
    BOOST_TEST(25 == **n27.parent());
    BOOST_TEST(27 == **n25.right());
    BOOST_TEST(22 == **n25.begin());
    BOOST_TEST(27 == **(n25.begin() + 1));
    BOOST_TEST(n25.begin() + 2 == n25.end());
    BOOST_TEST(27 == **n25.rbegin());
    BOOST_TEST(22 == **(n25.rbegin() + 1));
    BOOST_TEST(n25.rbegin() + 2 == n25.rend());

    ::odds_and_ends::node::in_order_tree_iterator<binary_tree_node> in_ord_fwd_itr(n13);

    BOOST_TEST(1 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(1 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);

    ::odds_and_ends::node::in_order_tree_iterator<
        binary_tree_node,
        ::boost::mpl::true_
    > in_ord_rev_itr(n13);

    BOOST_TEST(27 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(27 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);

    binary_tree_node::traits::pointer rotate_result = n08.rotate_right();

    BOOST_TEST(6 == **rotate_result);
    BOOST_TEST(6 == **n01.parent());
    BOOST_TEST(!n01.left());
    BOOST_TEST(!n01.right());
    BOOST_TEST(n01.begin() == n01.end());
    BOOST_TEST(n01.rbegin() == n01.rend());
    BOOST_TEST(13 == **n06.parent());
    BOOST_TEST(1 == **n06.left());
    BOOST_TEST(8 == **n06.right());
    BOOST_TEST(1 == **n06.begin());
    BOOST_TEST(8 == **(n06.begin() + 1));
    BOOST_TEST(n06.begin() + 2 == n06.end());
    BOOST_TEST(8 == **n06.rbegin());
    BOOST_TEST(1 == **(n06.rbegin() + 1));
    BOOST_TEST(n06.rbegin() + 2 == n06.rend());
    BOOST_TEST(6 == **n08.parent());
    BOOST_TEST(!n08.left());
    BOOST_TEST(11 == **n08.right());
    BOOST_TEST(11 == **n08.begin());
    BOOST_TEST(n08.begin() + 1 == n08.end());
    BOOST_TEST(11 == **n08.rbegin());
    BOOST_TEST(n08.rbegin() + 1 == n08.rend());
    BOOST_TEST(8 == **n11.parent());
    BOOST_TEST(!n11.left());
    BOOST_TEST(!n11.right());
    BOOST_TEST(n11.begin() == n11.end());
    BOOST_TEST(n11.rbegin() == n11.rend());
    BOOST_TEST(!n13.parent());
    BOOST_TEST(6 == **n13.left());
    BOOST_TEST(17 == **n13.right());
    BOOST_TEST(6 == **n13.begin());
    BOOST_TEST(17 == **(n13.begin() + 1));
    BOOST_TEST(n13.begin() + 2 == n13.end());
    BOOST_TEST(17 == **n13.rbegin());
    BOOST_TEST(6 == **(n13.rbegin() + 1));
    BOOST_TEST(n13.rbegin() + 2 == n13.rend());
    BOOST_TEST(17 == **n15.parent());
    BOOST_TEST(!n15.left());
    BOOST_TEST(!n15.right());
    BOOST_TEST(n15.begin() == n15.end());
    BOOST_TEST(n15.rbegin() == n15.rend());
    BOOST_TEST(13 == **n17.parent());
    BOOST_TEST(15 == **n17.left());
    BOOST_TEST(25 == **n17.right());
    BOOST_TEST(15 == **n17.begin());
    BOOST_TEST(25 == **(n17.begin() + 1));
    BOOST_TEST(n17.begin() + 2 == n17.end());
    BOOST_TEST(25 == **n17.rbegin());
    BOOST_TEST(15 == **(n17.rbegin() + 1));
    BOOST_TEST(n17.rbegin() + 2 == n17.rend());
    BOOST_TEST(25 == **n22.parent());
    BOOST_TEST(!n22.left());
    BOOST_TEST(!n22.right());
    BOOST_TEST(n22.begin() == n22.end());
    BOOST_TEST(n22.rbegin() == n22.rend());
    BOOST_TEST(17 == **n25.parent());
    BOOST_TEST(22 == **n25.left());
    BOOST_TEST(27 == **n25.right());
    BOOST_TEST(22 == **n25.begin());
    BOOST_TEST(27 == **(n25.begin() + 1));
    BOOST_TEST(n25.begin() + 2 == n25.end());
    BOOST_TEST(27 == **n25.rbegin());
    BOOST_TEST(22 == **(n25.rbegin() + 1));
    BOOST_TEST(n25.rbegin() + 2 == n25.rend());
    BOOST_TEST(25 == **n27.parent());
    BOOST_TEST(!n27.left());
    BOOST_TEST(!n27.right());
    BOOST_TEST(n27.begin() == n27.end());
    BOOST_TEST(n27.rbegin() == n27.rend());
    in_ord_fwd_itr = ::odds_and_ends::node::make_in_order_tree_iterator(n13);
    BOOST_TEST(1 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(1 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    in_ord_rev_itr = ::odds_and_ends::node::make_in_order_tree_reverse_iterator(n13);
    BOOST_TEST(27 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(27 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    rotate_result = n17.rotate_left();
    BOOST_TEST(25 == **rotate_result);
    BOOST_TEST(6 == **n01.parent());
    BOOST_TEST(!n01.left());
    BOOST_TEST(!n01.right());
    BOOST_TEST(n01.begin() == n01.end());
    BOOST_TEST(n01.rbegin() == n01.rend());
    BOOST_TEST(13 == **n06.parent());
    BOOST_TEST(1 == **n06.left());
    BOOST_TEST(8 == **n06.right());
    BOOST_TEST(1 == **n06.begin());
    BOOST_TEST(8 == **(n06.begin() + 1));
    BOOST_TEST(n06.begin() + 2 == n06.end());
    BOOST_TEST(8 == **n06.rbegin());
    BOOST_TEST(1 == **(n06.rbegin() + 1));
    BOOST_TEST(n06.rbegin() + 2 == n06.rend());
    BOOST_TEST(6 == **n08.parent());
    BOOST_TEST(!n08.left());
    BOOST_TEST(11 == **n08.right());
    BOOST_TEST(11 == **n08.begin());
    BOOST_TEST(n08.begin() + 1 == n08.end());
    BOOST_TEST(11 == **n08.rbegin());
    BOOST_TEST(n08.rbegin() + 1 == n08.rend());
    BOOST_TEST(8 == **n11.parent());
    BOOST_TEST(!n11.left());
    BOOST_TEST(!n11.right());
    BOOST_TEST(n11.begin() == n11.end());
    BOOST_TEST(n11.rbegin() == n11.rend());
    BOOST_TEST(!n13.parent());
    BOOST_TEST(6 == **n13.left());
    BOOST_TEST(25 == **n13.right());
    BOOST_TEST(6 == **n13.begin());
    BOOST_TEST(25 == **(n13.begin() + 1));
    BOOST_TEST(n13.begin() + 2 == n13.end());
    BOOST_TEST(25 == **n13.rbegin());
    BOOST_TEST(6 == **(n13.rbegin() + 1));
    BOOST_TEST(n13.rbegin() + 2 == n13.rend());
    BOOST_TEST(17 == **n15.parent());
    BOOST_TEST(!n15.left());
    BOOST_TEST(!n15.right());
    BOOST_TEST(n15.begin() == n15.end());
    BOOST_TEST(n15.rbegin() == n15.rend());
    BOOST_TEST(25 == **n17.parent());
    BOOST_TEST(15 == **n17.left());
    BOOST_TEST(22 == **n17.right());
    BOOST_TEST(15 == **n17.begin());
    BOOST_TEST(22 == **(n17.begin() + 1));
    BOOST_TEST(n17.begin() + 2 == n17.end());
    BOOST_TEST(22 == **n17.rbegin());
    BOOST_TEST(15 == **(n17.rbegin() + 1));
    BOOST_TEST(n17.rbegin() + 2 == n17.rend());
    BOOST_TEST(17 == **n22.parent());
    BOOST_TEST(!n22.left());
    BOOST_TEST(!n22.right());
    BOOST_TEST(n22.begin() == n22.end());
    BOOST_TEST(n22.rbegin() == n22.rend());
    BOOST_TEST(13 == **n25.parent());
    BOOST_TEST(17 == **n25.left());
    BOOST_TEST(27 == **n25.right());
    BOOST_TEST(17 == **n25.begin());
    BOOST_TEST(27 == **(n25.begin() + 1));
    BOOST_TEST(n25.begin() + 2 == n25.end());
    BOOST_TEST(27 == **n25.rbegin());
    BOOST_TEST(17 == **(n25.rbegin() + 1));
    BOOST_TEST(n25.rbegin() + 2 == n25.rend());
    BOOST_TEST(25 == **n27.parent());
    BOOST_TEST(!n27.left());
    BOOST_TEST(!n27.right());
    BOOST_TEST(n27.begin() == n27.end());
    BOOST_TEST(n27.rbegin() == n27.rend());
    in_ord_fwd_itr = ::odds_and_ends::node::make_in_order_tree_iterator(n13);
    BOOST_TEST(1 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(1 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    in_ord_rev_itr = ::odds_and_ends::node::make_in_order_tree_reverse_iterator(n13);
    BOOST_TEST(27 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(27 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    rotate_result = n06.rotate_left();
    BOOST_TEST(8 == **rotate_result);
    BOOST_TEST(6 == **n01.parent());
    BOOST_TEST(n01.begin() == n01.end());
    BOOST_TEST(n01.rbegin() == n01.rend());
    BOOST_TEST(8 == **n06.parent());
    BOOST_TEST(1 == **n06.left());
    BOOST_TEST(1 == **n06.begin());
    BOOST_TEST(n06.begin() + 1 == n06.end());
    BOOST_TEST(1 == **n06.rbegin());
    BOOST_TEST(n06.rbegin() + 1 == n06.rend());
    BOOST_TEST(13 == **n08.parent());
    BOOST_TEST(11 == **n08.right());
    BOOST_TEST(6 == **n08.begin());
    BOOST_TEST(11 == **(n08.begin() + 1));
    BOOST_TEST(n08.begin() + 2 == n08.end());
    BOOST_TEST(11 == **n08.rbegin());
    BOOST_TEST(6 == **(n08.rbegin() + 1));
    BOOST_TEST(n08.rbegin() + 2 == n08.rend());
    BOOST_TEST(8 == **n11.parent());
    BOOST_TEST(!n11.left());
    BOOST_TEST(!n11.right());
    BOOST_TEST(n11.begin() == n11.end());
    BOOST_TEST(n11.rbegin() == n11.rend());
    BOOST_TEST(!n13.parent());
    BOOST_TEST(8 == **n13.left());
    BOOST_TEST(25 == **n13.right());
    BOOST_TEST(8 == **n13.begin());
    BOOST_TEST(25 == **(n13.begin() + 1));
    BOOST_TEST(n13.begin() + 2 == n13.end());
    BOOST_TEST(25 == **n13.rbegin());
    BOOST_TEST(8 == **(n13.rbegin() + 1));
    BOOST_TEST(n13.rbegin() + 2 == n13.rend());
    BOOST_TEST(17 == **n15.parent());
    BOOST_TEST(!n15.left());
    BOOST_TEST(!n15.right());
    BOOST_TEST(n15.begin() == n15.end());
    BOOST_TEST(n15.rbegin() == n15.rend());
    BOOST_TEST(25 == **n17.parent());
    BOOST_TEST(15 == **n17.left());
    BOOST_TEST(22 == **n17.right());
    BOOST_TEST(15 == **n17.begin());
    BOOST_TEST(22 == **(n17.begin() + 1));
    BOOST_TEST(n17.begin() + 2 == n17.end());
    BOOST_TEST(22 == **n17.rbegin());
    BOOST_TEST(15 == **(n17.rbegin() + 1));
    BOOST_TEST(n17.rbegin() + 2 == n17.rend());
    BOOST_TEST(17 == **n22.parent());
    BOOST_TEST(!n22.left());
    BOOST_TEST(!n22.right());
    BOOST_TEST(n22.begin() == n22.end());
    BOOST_TEST(n22.rbegin() == n22.rend());
    BOOST_TEST(13 == **n25.parent());
    BOOST_TEST(17 == **n25.left());
    BOOST_TEST(27 == **n25.right());
    BOOST_TEST(17 == **n25.begin());
    BOOST_TEST(27 == **(n25.begin() + 1));
    BOOST_TEST(n25.begin() + 2 == n25.end());
    BOOST_TEST(27 == **n25.rbegin());
    BOOST_TEST(17 == **(n25.rbegin() + 1));
    BOOST_TEST(n25.rbegin() + 2 == n25.rend());
    BOOST_TEST(25 == **n27.parent());
    BOOST_TEST(!n27.left());
    BOOST_TEST(!n27.right());
    BOOST_TEST(n27.begin() == n27.end());
    BOOST_TEST(n27.rbegin() == n27.rend());
    in_ord_fwd_itr = ::odds_and_ends::node::make_in_order_tree_iterator(n13);
    BOOST_TEST(1 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(1 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    in_ord_rev_itr = ::odds_and_ends::node::make_in_order_tree_reverse_iterator(n13);
    BOOST_TEST(27 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(27 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    rotate_result = n25.rotate_right();
    BOOST_TEST(17 == **rotate_result);
    BOOST_TEST(6 == **n01.parent());
    BOOST_TEST(n01.begin() == n01.end());
    BOOST_TEST(n01.rbegin() == n01.rend());
    BOOST_TEST(8 == **n06.parent());
    BOOST_TEST(1 == **n06.left());
    BOOST_TEST(1 == **n06.begin());
    BOOST_TEST(n06.begin() + 1 == n06.end());
    BOOST_TEST(1 == **n06.rbegin());
    BOOST_TEST(n06.rbegin() + 1 == n06.rend());
    BOOST_TEST(13 == **n08.parent());
    BOOST_TEST(11 == **n08.right());
    BOOST_TEST(6 == **n08.begin());
    BOOST_TEST(11 == **(n08.begin() + 1));
    BOOST_TEST(n08.begin() + 2 == n08.end());
    BOOST_TEST(11 == **n08.rbegin());
    BOOST_TEST(6 == **(n08.rbegin() + 1));
    BOOST_TEST(n08.rbegin() + 2 == n08.rend());
    BOOST_TEST(8 == **n11.parent());
    BOOST_TEST(!n11.left());
    BOOST_TEST(!n11.right());
    BOOST_TEST(n11.begin() == n11.end());
    BOOST_TEST(n11.rbegin() == n11.rend());
    BOOST_TEST(!n13.parent());
    BOOST_TEST(8 == **n13.left());
    BOOST_TEST(17 == **n13.right());
    BOOST_TEST(8 == **n13.begin());
    BOOST_TEST(17 == **(n13.begin() + 1));
    BOOST_TEST(n13.begin() + 2 == n13.end());
    BOOST_TEST(17 == **n13.rbegin());
    BOOST_TEST(8 == **(n13.rbegin() + 1));
    BOOST_TEST(n13.rbegin() + 2 == n13.rend());
    BOOST_TEST(17 == **n15.parent());
    BOOST_TEST(!n15.left());
    BOOST_TEST(!n15.right());
    BOOST_TEST(n15.begin() == n15.end());
    BOOST_TEST(n15.rbegin() == n15.rend());
    BOOST_TEST(13 == **n17.parent());
    BOOST_TEST(15 == **n17.left());
    BOOST_TEST(25 == **n17.right());
    BOOST_TEST(15 == **n17.begin());
    BOOST_TEST(25 == **(n17.begin() + 1));
    BOOST_TEST(n17.begin() + 2 == n17.end());
    BOOST_TEST(25 == **n17.rbegin());
    BOOST_TEST(15 == **(n17.rbegin() + 1));
    BOOST_TEST(n17.rbegin() + 2 == n17.rend());
    BOOST_TEST(25 == **n22.parent());
    BOOST_TEST(!n22.left());
    BOOST_TEST(!n22.right());
    BOOST_TEST(n22.begin() == n22.end());
    BOOST_TEST(n22.rbegin() == n22.rend());
    BOOST_TEST(17 == **n25.parent());
    BOOST_TEST(22 == **n25.left());
    BOOST_TEST(27 == **n25.right());
    BOOST_TEST(22 == **n25.begin());
    BOOST_TEST(27 == **(n25.begin() + 1));
    BOOST_TEST(n25.begin() + 2 == n25.end());
    BOOST_TEST(27 == **n25.rbegin());
    BOOST_TEST(22 == **(n25.rbegin() + 1));
    BOOST_TEST(n25.rbegin() + 2 == n25.rend());
    BOOST_TEST(25 == **n27.parent());
    BOOST_TEST(!n27.left());
    BOOST_TEST(!n27.right());
    BOOST_TEST(n27.begin() == n27.end());
    BOOST_TEST(n27.rbegin() == n27.rend());
    in_ord_fwd_itr = ::odds_and_ends::node::make_in_order_tree_iterator(n13);
    BOOST_TEST(1 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(1 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(6 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(8 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(11 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(13 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(15 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(17 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(22 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(25 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    --in_ord_fwd_itr;
    BOOST_TEST(27 == **in_ord_fwd_itr);
    ++in_ord_fwd_itr;
    BOOST_TEST(!in_ord_fwd_itr);
    in_ord_rev_itr = ::odds_and_ends::node::make_in_order_tree_reverse_iterator(n13);
    BOOST_TEST(27 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(27 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(25 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(22 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(17 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(15 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(13 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(11 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(8 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(6 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
    --in_ord_rev_itr;
    BOOST_TEST(1 == **in_ord_rev_itr);
    ++in_ord_rev_itr;
    BOOST_TEST(!in_ord_rev_itr);
}

int main(int argc, char** argv)
{
    test_00();
    test_01();
    return ::boost::report_errors();
}

