// Copyright (C) 2026 Cromwell D. Enage

#include <odds_and_ends/node/data.hpp>
#include <odds_and_ends/node/tree/base.hpp>
#include <odds_and_ends/node/tree/associative.hpp>
#include <odds_and_ends/node/tree/with_size.hpp>
#include <odds_and_ends/composite_type/composite_type.hpp>
#include <boost/mpl/deque.hpp>
#include <boost/mpl/quote.hpp>
#include <boost/core/lightweight_test.hpp>

typedef ::odds_and_ends::composite_type::composite_type<
    ::boost::mpl::deque<
        ::odds_and_ends::node::data<int const>,
        ::odds_and_ends::node::tree::base<>,
        ::odds_and_ends::node::tree::associative<char>,
        ::odds_and_ends::node::tree::with_size<>
    >
> associative_tree_node;

void test_00()
{
    associative_tree_node atn_n03(-3);
    associative_tree_node atn_n02(-2);
    associative_tree_node atn_n01(-1);
    associative_tree_node atn_o00(0);
    associative_tree_node atn_p01(1);
    associative_tree_node atn_p02(2);
    associative_tree_node atn_p03(3);
    associative_tree_node atn_p04(4);
    associative_tree_node atn_p05(5);
    associative_tree_node atn_p06(6);
    associative_tree_node atn_p07(7);
    associative_tree_node atn_p08(8);
    associative_tree_node atn_p09(9);
    associative_tree_node atn_p10(10);
    associative_tree_node atn_p11(11);
    associative_tree_node atn_p12(12);
    associative_tree_node atn_p13(13);

    BOOST_TEST(-3 == *atn_n03);
    BOOST_TEST(!atn_n03.parent());
    BOOST_TEST(atn_n03.cbegin() == atn_n03.cend());
    BOOST_TEST(1 == atn_n03.size());
    BOOST_TEST(-2 == *atn_n02);
    BOOST_TEST(!atn_n02.parent());
    BOOST_TEST(atn_n02.cbegin() == atn_n02.cend());
    BOOST_TEST(1 == atn_n02.size());
    BOOST_TEST(-1 == *atn_n01);
    BOOST_TEST(!atn_n01.parent());
    BOOST_TEST(atn_n01.cbegin() == atn_n01.cend());
    BOOST_TEST(1 == atn_n01.size());
    BOOST_TEST(0 == *atn_o00);
    BOOST_TEST(!atn_o00.parent());
    BOOST_TEST(atn_o00.cbegin() == atn_o00.cend());
    BOOST_TEST(1 == atn_o00.size());
    BOOST_TEST(1 == *atn_p01);
    BOOST_TEST(!atn_p01.parent());
    BOOST_TEST(atn_p01.cbegin() == atn_p01.cend());
    BOOST_TEST(1 == atn_p01.size());
    BOOST_TEST(2 == *atn_p02);
    BOOST_TEST(!atn_p02.parent());
    BOOST_TEST(atn_p02.cbegin() == atn_p02.cend());
    BOOST_TEST(1 == atn_p02.size());
    BOOST_TEST(3 == *atn_p03);
    BOOST_TEST(!atn_p03.parent());
    BOOST_TEST(atn_p03.cbegin() == atn_p03.cend());
    BOOST_TEST(1 == atn_p03.size());
    BOOST_TEST(4 == *atn_p04);
    BOOST_TEST(!atn_p04.parent());
    BOOST_TEST(atn_p04.cbegin() == atn_p04.cend());
    BOOST_TEST(1 == atn_p04.size());
    BOOST_TEST(5 == *atn_p05);
    BOOST_TEST(!atn_p05.parent());
    BOOST_TEST(atn_p05.cbegin() == atn_p05.cend());
    BOOST_TEST(1 == atn_p05.size());
    BOOST_TEST(6 == *atn_p06);
    BOOST_TEST(!atn_p06.parent());
    BOOST_TEST(atn_p06.cbegin() == atn_p06.cend());
    BOOST_TEST(1 == atn_p06.size());
    BOOST_TEST(7 == *atn_p07);
    BOOST_TEST(!atn_p07.parent());
    BOOST_TEST(atn_p07.cbegin() == atn_p07.cend());
    BOOST_TEST(1 == atn_p07.size());
    BOOST_TEST(8 == *atn_p08);
    BOOST_TEST(!atn_p08.parent());
    BOOST_TEST(atn_p08.cbegin() == atn_p08.cend());
    BOOST_TEST(1 == atn_p08.size());
    BOOST_TEST(9 == *atn_p09);
    BOOST_TEST(!atn_p09.parent());
    BOOST_TEST(atn_p09.cbegin() == atn_p09.cend());
    BOOST_TEST(1 == atn_p09.size());
    BOOST_TEST(10 == *atn_p10);
    BOOST_TEST(!atn_p10.parent());
    BOOST_TEST(atn_p10.cbegin() == atn_p10.cend());
    BOOST_TEST(1 == atn_p10.size());
    BOOST_TEST(11 == *atn_p11);
    BOOST_TEST(!atn_p11.parent());
    BOOST_TEST(atn_p11.cbegin() == atn_p11.cend());
    BOOST_TEST(1 == atn_p11.size());
    BOOST_TEST(12 == *atn_p12);
    BOOST_TEST(!atn_p12.parent());
    BOOST_TEST(atn_p12.cbegin() == atn_p12.cend());
    BOOST_TEST(1 == atn_p12.size());
    BOOST_TEST(13 == *atn_p13);
    BOOST_TEST(!atn_p13.parent());
    BOOST_TEST(atn_p13.cbegin() == atn_p13.cend());
    BOOST_TEST(1 == atn_p13.size());
    atn_o00.set('i', atn_n03);
    BOOST_TEST('i' == atn_o00.get('i')->key());
    BOOST_TEST(-3 == **atn_o00.get('i'));
    BOOST_TEST(0 == **atn_o00.get('i')->parent());
    BOOST_TEST(0 == **atn_n03.parent());

    associative_tree_node::traits::child_const_iterator c_fwd_itr = atn_o00.cbegin();

    BOOST_TEST('i' == c_fwd_itr->first);
    BOOST_TEST('i' == c_fwd_itr->second->key());
    BOOST_TEST(-3 == **c_fwd_itr->second);
    BOOST_TEST(0 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_o00.cend());

    associative_tree_node::traits::child_const_reverse_iterator c_rev_itr = atn_o00.crbegin();

    BOOST_TEST('i' == c_rev_itr->first);
    BOOST_TEST('i' == c_rev_itr->second->key());
    BOOST_TEST(-3 == **c_rev_itr->second);
    BOOST_TEST(0 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_o00.crend());
    BOOST_TEST(2 == atn_o00.size());
    atn_n03.set('n', atn_p07);
    BOOST_TEST('n' == atn_n03.get('n')->key());
    BOOST_TEST(7 == **atn_n03.get('n'));
    BOOST_TEST(-3 == **atn_n03.get('n')->parent());
    BOOST_TEST(-3 == **atn_p07.parent());
    c_fwd_itr = atn_n03.cbegin();
    BOOST_TEST('n' == c_fwd_itr->first);
    BOOST_TEST('n' == c_fwd_itr->second->key());
    BOOST_TEST(7 == **c_fwd_itr->second);
    BOOST_TEST(-3 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n03.cend());
    c_rev_itr = atn_n03.crbegin();
    BOOST_TEST('n' == c_rev_itr->first);
    BOOST_TEST('n' == c_rev_itr->second->key());
    BOOST_TEST(7 == **c_rev_itr->second);
    BOOST_TEST(-3 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n03.crend());
    BOOST_TEST(3 == atn_o00.size());
    BOOST_TEST(2 == atn_n03.size());
    atn_p07.set('k', atn_p09);
    BOOST_TEST('k' == atn_p07.get('k')->key());
    BOOST_TEST(9 == **atn_p07.get('k'));
    BOOST_TEST(7 == **atn_p07.get('k')->parent());
    BOOST_TEST(7 == **atn_p09.parent());
    c_fwd_itr = atn_p07.cbegin();
    BOOST_TEST('k' == c_fwd_itr->first);
    BOOST_TEST('k' == c_fwd_itr->second->key());
    BOOST_TEST(9 == **c_fwd_itr->second);
    BOOST_TEST(7 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_p07.cend());
    c_rev_itr = atn_p07.crbegin();
    BOOST_TEST('k' == c_rev_itr->first);
    BOOST_TEST('k' == c_rev_itr->second->key());
    BOOST_TEST(9 == **c_rev_itr->second);
    BOOST_TEST(7 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_p07.crend());
    BOOST_TEST(4 == atn_o00.size());
    BOOST_TEST(3 == atn_n03.size());
    BOOST_TEST(2 == atn_p07.size());
    atn_p07.set('n', atn_p10);
    BOOST_TEST('n' == atn_p07.get('n')->key());
    BOOST_TEST(10 == **atn_p07.get('n'));
    BOOST_TEST(7 == **atn_p07.get('n')->parent());
    BOOST_TEST(7 == **atn_p10.parent());
    c_fwd_itr = atn_p07.cbegin();
    BOOST_TEST('k' == c_fwd_itr->first);
    BOOST_TEST('k' == c_fwd_itr->second->key());
    BOOST_TEST(9 == **c_fwd_itr->second);
    BOOST_TEST(7 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('n' == c_fwd_itr->first);
    BOOST_TEST('n' == c_fwd_itr->second->key());
    BOOST_TEST(10 == **c_fwd_itr->second);
    BOOST_TEST(7 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_p07.cend());
    c_rev_itr = atn_p07.crbegin();
    BOOST_TEST('n' == c_rev_itr->first);
    BOOST_TEST('n' == c_rev_itr->second->key());
    BOOST_TEST(10 == **c_rev_itr->second);
    BOOST_TEST(7 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('k' == c_rev_itr->first);
    BOOST_TEST('k' == c_rev_itr->second->key());
    BOOST_TEST(9 == **c_rev_itr->second);
    BOOST_TEST(7 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_p07.crend());
    BOOST_TEST(5 == atn_o00.size());
    BOOST_TEST(4 == atn_n03.size());
    BOOST_TEST(3 == atn_p07.size());
    atn_n03.set('s', atn_p11);
    BOOST_TEST('s' == atn_n03.get('s')->key());
    BOOST_TEST(11 == **atn_n03.get('s'));
    BOOST_TEST(-3 == **atn_n03.get('s')->parent());
    BOOST_TEST(-3 == **atn_p11.parent());
    c_fwd_itr = atn_n03.cbegin();
    BOOST_TEST('n' == c_fwd_itr->first);
    BOOST_TEST('n' == c_fwd_itr->second->key());
    BOOST_TEST(7 == **c_fwd_itr->second);
    BOOST_TEST(-3 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('s' == c_fwd_itr->first);
    BOOST_TEST('s' == c_fwd_itr->second->key());
    BOOST_TEST(11 == **c_fwd_itr->second);
    BOOST_TEST(-3 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n03.cend());
    c_rev_itr = atn_n03.crbegin();
    BOOST_TEST('s' == c_rev_itr->first);
    BOOST_TEST('s' == c_rev_itr->second->key());
    BOOST_TEST(11 == **c_rev_itr->second);
    BOOST_TEST(-3 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('n' == c_rev_itr->first);
    BOOST_TEST('n' == c_rev_itr->second->key());
    BOOST_TEST(7 == **c_rev_itr->second);
    BOOST_TEST(-3 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n03.crend());
    BOOST_TEST(6 == atn_o00.size());
    BOOST_TEST(5 == atn_n03.size());
    atn_n03.set('t', atn_p12);
    BOOST_TEST('t' == atn_n03.get('t')->key());
    BOOST_TEST(12 == **atn_n03.get('t'));
    BOOST_TEST(-3 == **atn_n03.get('t')->parent());
    BOOST_TEST(-3 == **atn_p12.parent());
    c_fwd_itr = atn_n03.cbegin();
    BOOST_TEST('n' == c_fwd_itr->first);
    BOOST_TEST('n' == c_fwd_itr->second->key());
    BOOST_TEST(7 == **c_fwd_itr->second);
    BOOST_TEST(-3 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('s' == c_fwd_itr->first);
    BOOST_TEST('s' == c_fwd_itr->second->key());
    BOOST_TEST(11 == **c_fwd_itr->second);
    BOOST_TEST(-3 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('t' == c_fwd_itr->first);
    BOOST_TEST('t' == c_fwd_itr->second->key());
    BOOST_TEST(12 == **c_fwd_itr->second);
    BOOST_TEST(-3 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n03.cend());
    c_rev_itr = atn_n03.crbegin();
    BOOST_TEST('t' == c_rev_itr->first);
    BOOST_TEST('t' == c_rev_itr->second->key());
    BOOST_TEST(12 == **c_rev_itr->second);
    BOOST_TEST(-3 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('s' == c_rev_itr->first);
    BOOST_TEST('s' == c_rev_itr->second->key());
    BOOST_TEST(11 == **c_rev_itr->second);
    BOOST_TEST(-3 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('n' == c_rev_itr->first);
    BOOST_TEST('n' == c_rev_itr->second->key());
    BOOST_TEST(7 == **c_rev_itr->second);
    BOOST_TEST(-3 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n03.crend());
    BOOST_TEST(7 == atn_o00.size());
    BOOST_TEST(6 == atn_n03.size());
    atn_o00.set('t', atn_n01);
    BOOST_TEST('t' == atn_o00.get('t')->key());
    BOOST_TEST(-1 == **atn_o00.get('t'));
    BOOST_TEST(0 == **atn_o00.get('t')->parent());
    BOOST_TEST(0 == **atn_n01.parent());
    c_fwd_itr = atn_o00.cbegin();
    BOOST_TEST('i' == c_fwd_itr->first);
    BOOST_TEST('i' == c_fwd_itr->second->key());
    BOOST_TEST(-3 == **c_fwd_itr->second);
    BOOST_TEST(0 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('t' == c_fwd_itr->first);
    BOOST_TEST('t' == c_fwd_itr->second->key());
    BOOST_TEST(-1 == **c_fwd_itr->second);
    BOOST_TEST(0 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_o00.cend());
    c_rev_itr = atn_o00.crbegin();
    BOOST_TEST('t' == c_rev_itr->first);
    BOOST_TEST('t' == c_rev_itr->second->key());
    BOOST_TEST(-1 == **c_rev_itr->second);
    BOOST_TEST(0 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('i' == c_rev_itr->first);
    BOOST_TEST('i' == c_rev_itr->second->key());
    BOOST_TEST(-3 == **c_rev_itr->second);
    BOOST_TEST(0 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_o00.crend());
    BOOST_TEST(8 == atn_o00.size());
    atn_n01.set('o', atn_p08);
    BOOST_TEST('o' == atn_n01.get('o')->key());
    BOOST_TEST(8 == **atn_n01.get('o'));
    BOOST_TEST(-1 == **atn_n01.get('o')->parent());
    BOOST_TEST(-1 == **atn_p08.parent());
    c_fwd_itr = atn_n01.cbegin();
    BOOST_TEST('o' == c_fwd_itr->first);
    BOOST_TEST('o' == c_fwd_itr->second->key());
    BOOST_TEST(8 == **c_fwd_itr->second);
    BOOST_TEST(-1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n01.cend());
    c_rev_itr = atn_n01.crbegin();
    BOOST_TEST('o' == c_rev_itr->first);
    BOOST_TEST('o' == c_rev_itr->second->key());
    BOOST_TEST(8 == **c_rev_itr->second);
    BOOST_TEST(-1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n01.crend());
    BOOST_TEST(9 == atn_o00.size());
    BOOST_TEST(2 == atn_n01.size());
    atn_n01.set('e', atn_n02);
    BOOST_TEST('e' == atn_n01.get('e')->key());
    BOOST_TEST(-2 == **atn_n01.get('e'));
    BOOST_TEST(-1 == **atn_n01.get('e')->parent());
    BOOST_TEST(-1 == **atn_n02.parent());
    c_fwd_itr = atn_n01.cbegin();
    BOOST_TEST('e' == c_fwd_itr->first);
    BOOST_TEST('e' == c_fwd_itr->second->key());
    BOOST_TEST(-2 == **c_fwd_itr->second);
    BOOST_TEST(-1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('o' == c_fwd_itr->first);
    BOOST_TEST('o' == c_fwd_itr->second->key());
    BOOST_TEST(8 == **c_fwd_itr->second);
    BOOST_TEST(-1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n01.cend());
    c_rev_itr = atn_n01.crbegin();
    BOOST_TEST('o' == c_rev_itr->first);
    BOOST_TEST('o' == c_rev_itr->second->key());
    BOOST_TEST(8 == **c_rev_itr->second);
    BOOST_TEST(-1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('e' == c_rev_itr->first);
    BOOST_TEST('e' == c_rev_itr->second->key());
    BOOST_TEST(-2 == **c_rev_itr->second);
    BOOST_TEST(-1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n01.crend());
    BOOST_TEST(10 == atn_o00.size());
    BOOST_TEST(3 == atn_n01.size());
    atn_n02.set('d', atn_p05);
    BOOST_TEST('d' == atn_n02.get('d')->key());
    BOOST_TEST(5 == **atn_n02.get('d'));
    BOOST_TEST(-2 == **atn_n02.get('d')->parent());
    BOOST_TEST(-2 == **atn_p05.parent());
    c_fwd_itr = atn_n02.cbegin();
    BOOST_TEST('d' == c_fwd_itr->first);
    BOOST_TEST('d' == c_fwd_itr->second->key());
    BOOST_TEST(5 == **c_fwd_itr->second);
    BOOST_TEST(-2 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n02.cend());
    c_rev_itr = atn_n02.crbegin();
    BOOST_TEST('d' == c_rev_itr->first);
    BOOST_TEST('d' == c_rev_itr->second->key());
    BOOST_TEST(5 == **c_rev_itr->second);
    BOOST_TEST(-2 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n02.crend());
    BOOST_TEST(11 == atn_o00.size());
    BOOST_TEST(4 == atn_n01.size());
    BOOST_TEST(2 == atn_n02.size());
    atn_n02.set('n', atn_p06);
    BOOST_TEST('n' == atn_n02.get('n')->key());
    BOOST_TEST(6 == **atn_n02.get('n'));
    BOOST_TEST(-2 == **atn_n02.get('n')->parent());
    BOOST_TEST(-2 == **atn_p06.parent());
    c_fwd_itr = atn_n02.cbegin();
    BOOST_TEST('d' == c_fwd_itr->first);
    BOOST_TEST('d' == c_fwd_itr->second->key());
    BOOST_TEST(5 == **c_fwd_itr->second);
    BOOST_TEST(-2 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('n' == c_fwd_itr->first);
    BOOST_TEST('n' == c_fwd_itr->second->key());
    BOOST_TEST(6 == **c_fwd_itr->second);
    BOOST_TEST(-2 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n02.cend());
    c_rev_itr = atn_n02.crbegin();
    BOOST_TEST('n' == c_rev_itr->first);
    BOOST_TEST('n' == c_rev_itr->second->key());
    BOOST_TEST(6 == **c_rev_itr->second);
    BOOST_TEST(-2 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('d' == c_rev_itr->first);
    BOOST_TEST('d' == c_rev_itr->second->key());
    BOOST_TEST(5 == **c_rev_itr->second);
    BOOST_TEST(-2 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n02.crend());
    BOOST_TEST(12 == atn_o00.size());
    BOOST_TEST(5 == atn_n01.size());
    BOOST_TEST(3 == atn_n02.size());
    atn_n02.set('a', atn_p01);
    BOOST_TEST('a' == atn_n02.get('a')->key());
    BOOST_TEST(1 == **atn_n02.get('a'));
    BOOST_TEST(-2 == **atn_n02.get('a')->parent());
    BOOST_TEST(-2 == **atn_p01.parent());
    c_fwd_itr = atn_n02.cbegin();
    BOOST_TEST('a' == c_fwd_itr->first);
    BOOST_TEST('a' == c_fwd_itr->second->key());
    BOOST_TEST(1 == **c_fwd_itr->second);
    BOOST_TEST(-2 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('d' == c_fwd_itr->first);
    BOOST_TEST('d' == c_fwd_itr->second->key());
    BOOST_TEST(5 == **c_fwd_itr->second);
    BOOST_TEST(-2 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('n' == c_fwd_itr->first);
    BOOST_TEST('n' == c_fwd_itr->second->key());
    BOOST_TEST(6 == **c_fwd_itr->second);
    BOOST_TEST(-2 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n02.cend());
    c_rev_itr = atn_n02.crbegin();
    BOOST_TEST('n' == c_rev_itr->first);
    BOOST_TEST('n' == c_rev_itr->second->key());
    BOOST_TEST(6 == **c_rev_itr->second);
    BOOST_TEST(-2 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('d' == c_rev_itr->first);
    BOOST_TEST('d' == c_rev_itr->second->key());
    BOOST_TEST(5 == **c_rev_itr->second);
    BOOST_TEST(-2 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('a' == c_rev_itr->first);
    BOOST_TEST('a' == c_rev_itr->second->key());
    BOOST_TEST(1 == **c_rev_itr->second);
    BOOST_TEST(-2 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n02.crend());
    BOOST_TEST(13 == atn_o00.size());
    BOOST_TEST(6 == atn_n01.size());
    BOOST_TEST(4 == atn_n02.size());
    atn_p01.set('l', atn_p02);
    BOOST_TEST('l' == atn_p01.get('l')->key());
    BOOST_TEST(2 == **atn_p01.get('l'));
    BOOST_TEST(1 == **atn_p01.get('l')->parent());
    BOOST_TEST(1 == **atn_p02.parent());
    c_fwd_itr = atn_p01.cbegin();
    BOOST_TEST('l' == c_fwd_itr->first);
    BOOST_TEST('l' == c_fwd_itr->second->key());
    BOOST_TEST(2 == **c_fwd_itr->second);
    BOOST_TEST(1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_p01.cend());
    c_rev_itr = atn_p01.crbegin();
    BOOST_TEST('l' == c_rev_itr->first);
    BOOST_TEST('l' == c_rev_itr->second->key());
    BOOST_TEST(2 == **c_rev_itr->second);
    BOOST_TEST(1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_p01.crend());
    BOOST_TEST(14 == atn_o00.size());
    BOOST_TEST(7 == atn_n01.size());
    BOOST_TEST(5 == atn_n02.size());
    BOOST_TEST(2 == atn_p01.size());
    atn_p01.set('m', atn_p03);
    BOOST_TEST('m' == atn_p01.get('m')->key());
    BOOST_TEST(3 == **atn_p01.get('m'));
    BOOST_TEST(1 == **atn_p01.get('m')->parent());
    BOOST_TEST(1 == **atn_p03.parent());
    c_fwd_itr = atn_p01.cbegin();
    BOOST_TEST('l' == c_fwd_itr->first);
    BOOST_TEST('l' == c_fwd_itr->second->key());
    BOOST_TEST(2 == **c_fwd_itr->second);
    BOOST_TEST(1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('m' == c_fwd_itr->first);
    BOOST_TEST('m' == c_fwd_itr->second->key());
    BOOST_TEST(3 == **c_fwd_itr->second);
    BOOST_TEST(1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_p01.cend());
    c_rev_itr = atn_p01.crbegin();
    BOOST_TEST('m' == c_rev_itr->first);
    BOOST_TEST('m' == c_rev_itr->second->key());
    BOOST_TEST(3 == **c_rev_itr->second);
    BOOST_TEST(1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('l' == c_rev_itr->first);
    BOOST_TEST('l' == c_rev_itr->second->key());
    BOOST_TEST(2 == **c_rev_itr->second);
    BOOST_TEST(1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_p01.crend());
    BOOST_TEST(15 == atn_o00.size());
    BOOST_TEST(8 == atn_n01.size());
    BOOST_TEST(6 == atn_n02.size());
    BOOST_TEST(3 == atn_p01.size());
    atn_p01.set('r', atn_p04);
    BOOST_TEST('r' == atn_p01.get('r')->key());
    BOOST_TEST(4 == **atn_p01.get('r'));
    BOOST_TEST(1 == **atn_p01.get('r')->parent());
    BOOST_TEST(1 == **atn_p04.parent());
    c_fwd_itr = atn_p01.cbegin();
    BOOST_TEST('l' == c_fwd_itr->first);
    BOOST_TEST('l' == c_fwd_itr->second->key());
    BOOST_TEST(2 == **c_fwd_itr->second);
    BOOST_TEST(1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('m' == c_fwd_itr->first);
    BOOST_TEST('m' == c_fwd_itr->second->key());
    BOOST_TEST(3 == **c_fwd_itr->second);
    BOOST_TEST(1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('r' == c_fwd_itr->first);
    BOOST_TEST('r' == c_fwd_itr->second->key());
    BOOST_TEST(4 == **c_fwd_itr->second);
    BOOST_TEST(1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_p01.cend());
    c_rev_itr = atn_p01.crbegin();
    BOOST_TEST('r' == c_rev_itr->first);
    BOOST_TEST('r' == c_rev_itr->second->key());
    BOOST_TEST(4 == **c_rev_itr->second);
    BOOST_TEST(1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('m' == c_rev_itr->first);
    BOOST_TEST('m' == c_rev_itr->second->key());
    BOOST_TEST(3 == **c_rev_itr->second);
    BOOST_TEST(1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('l' == c_rev_itr->first);
    BOOST_TEST('l' == c_rev_itr->second->key());
    BOOST_TEST(2 == **c_rev_itr->second);
    BOOST_TEST(1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_p01.crend());
    BOOST_TEST(16 == atn_o00.size());
    BOOST_TEST(9 == atn_n01.size());
    BOOST_TEST(7 == atn_n02.size());
    BOOST_TEST(4 == atn_p01.size());
    atn_o00.set('A', atn_p13);
    BOOST_TEST('A' == atn_o00.get('A')->key());
    BOOST_TEST(13 == **atn_o00.get('A'));
    BOOST_TEST(0 == **atn_o00.get('A')->parent());
    BOOST_TEST(0 == **atn_p13.parent());
    c_fwd_itr = atn_o00.cbegin();
    BOOST_TEST('A' == c_fwd_itr->first);
    BOOST_TEST('A' == c_fwd_itr->second->key());
    BOOST_TEST(13 == **c_fwd_itr->second);
    BOOST_TEST(0 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('i' == c_fwd_itr->first);
    BOOST_TEST('i' == c_fwd_itr->second->key());
    BOOST_TEST(-3 == **c_fwd_itr->second);
    BOOST_TEST(0 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('t' == c_fwd_itr->first);
    BOOST_TEST('t' == c_fwd_itr->second->key());
    BOOST_TEST(-1 == **c_fwd_itr->second);
    BOOST_TEST(0 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_o00.cend());
    c_rev_itr = atn_o00.crbegin();
    BOOST_TEST('t' == c_rev_itr->first);
    BOOST_TEST('t' == c_rev_itr->second->key());
    BOOST_TEST(-1 == **c_rev_itr->second);
    BOOST_TEST(0 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('i' == c_rev_itr->first);
    BOOST_TEST('i' == c_rev_itr->second->key());
    BOOST_TEST(-3 == **c_rev_itr->second);
    BOOST_TEST(0 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('A' == c_rev_itr->first);
    BOOST_TEST('A' == c_rev_itr->second->key());
    BOOST_TEST(13 == **c_rev_itr->second);
    BOOST_TEST(0 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_o00.crend());
    BOOST_TEST(17 == atn_o00.size());
    atn_n03.swap(atn_p07);
    BOOST_TEST(7 == **atn_n03.parent());
    BOOST_TEST(0 == **atn_p07.parent());
    BOOST_TEST(7 == **atn_o00.get('i'));
    c_fwd_itr = atn_n03.cbegin();
    BOOST_TEST('k' == c_fwd_itr->first);
    BOOST_TEST('k' == c_fwd_itr->second->key());
    BOOST_TEST(9 == **c_fwd_itr->second);
    BOOST_TEST(-3 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('n' == c_fwd_itr->first);
    BOOST_TEST('n' == c_fwd_itr->second->key());
    BOOST_TEST(10 == **c_fwd_itr->second);
    BOOST_TEST(-3 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n03.cend());
    c_rev_itr = atn_n03.crbegin();
    BOOST_TEST('n' == c_rev_itr->first);
    BOOST_TEST('n' == c_rev_itr->second->key());
    BOOST_TEST(10 == **c_rev_itr->second);
    BOOST_TEST(-3 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('k' == c_rev_itr->first);
    BOOST_TEST('k' == c_rev_itr->second->key());
    BOOST_TEST(9 == **c_rev_itr->second);
    BOOST_TEST(-3 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n03.crend());
    c_fwd_itr = atn_p07.cbegin();
    BOOST_TEST('n' == c_fwd_itr->first);
    BOOST_TEST('n' == c_fwd_itr->second->key());
    BOOST_TEST(-3 == **c_fwd_itr->second);
    BOOST_TEST(7 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('s' == c_fwd_itr->first);
    BOOST_TEST('s' == c_fwd_itr->second->key());
    BOOST_TEST(11 == **c_fwd_itr->second);
    BOOST_TEST(7 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('t' == c_fwd_itr->first);
    BOOST_TEST('t' == c_fwd_itr->second->key());
    BOOST_TEST(12 == **c_fwd_itr->second);
    BOOST_TEST(7 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_p07.cend());
    c_rev_itr = atn_p07.crbegin();
    BOOST_TEST('t' == c_rev_itr->first);
    BOOST_TEST('t' == c_rev_itr->second->key());
    BOOST_TEST(12 == **c_rev_itr->second);
    BOOST_TEST(7 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('s' == c_rev_itr->first);
    BOOST_TEST('s' == c_rev_itr->second->key());
    BOOST_TEST(11 == **c_rev_itr->second);
    BOOST_TEST(7 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('n' == c_rev_itr->first);
    BOOST_TEST('n' == c_rev_itr->second->key());
    BOOST_TEST(-3 == **c_rev_itr->second);
    BOOST_TEST(7 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_p07.crend());
    BOOST_TEST(17 == atn_o00.size());
    BOOST_TEST(3 == atn_n03.size());
    BOOST_TEST(6 == atn_p07.size());
    atn_p01.swap(atn_n02);
    BOOST_TEST(-1 == **atn_p01.parent());
    BOOST_TEST(1 == **atn_n02.parent());
    BOOST_TEST(1 == **atn_n01.get('e'));
    c_fwd_itr = atn_n02.cbegin();
    BOOST_TEST('l' == c_fwd_itr->first);
    BOOST_TEST('l' == c_fwd_itr->second->key());
    BOOST_TEST(2 == **c_fwd_itr->second);
    BOOST_TEST(-2 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('m' == c_fwd_itr->first);
    BOOST_TEST('m' == c_fwd_itr->second->key());
    BOOST_TEST(3 == **c_fwd_itr->second);
    BOOST_TEST(-2 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('r' == c_fwd_itr->first);
    BOOST_TEST('r' == c_fwd_itr->second->key());
    BOOST_TEST(4 == **c_fwd_itr->second);
    BOOST_TEST(-2 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n02.cend());
    c_rev_itr = atn_n02.crbegin();
    BOOST_TEST('r' == c_rev_itr->first);
    BOOST_TEST('r' == c_rev_itr->second->key());
    BOOST_TEST(4 == **c_rev_itr->second);
    BOOST_TEST(-2 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('m' == c_rev_itr->first);
    BOOST_TEST('m' == c_rev_itr->second->key());
    BOOST_TEST(3 == **c_rev_itr->second);
    BOOST_TEST(-2 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('l' == c_rev_itr->first);
    BOOST_TEST('l' == c_rev_itr->second->key());
    BOOST_TEST(2 == **c_rev_itr->second);
    BOOST_TEST(-2 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n02.crend());
    c_fwd_itr = atn_p01.cbegin();
    BOOST_TEST('a' == c_fwd_itr->first);
    BOOST_TEST('a' == c_fwd_itr->second->key());
    BOOST_TEST(-2 == **c_fwd_itr->second);
    BOOST_TEST(1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('d' == c_fwd_itr->first);
    BOOST_TEST('d' == c_fwd_itr->second->key());
    BOOST_TEST(5 == **c_fwd_itr->second);
    BOOST_TEST(1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('n' == c_fwd_itr->first);
    BOOST_TEST('n' == c_fwd_itr->second->key());
    BOOST_TEST(6 == **c_fwd_itr->second);
    BOOST_TEST(1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_p01.cend());
    c_rev_itr = atn_p01.crbegin();
    BOOST_TEST('n' == c_rev_itr->first);
    BOOST_TEST('n' == c_rev_itr->second->key());
    BOOST_TEST(6 == **c_rev_itr->second);
    BOOST_TEST(1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('d' == c_rev_itr->first);
    BOOST_TEST('d' == c_rev_itr->second->key());
    BOOST_TEST(5 == **c_rev_itr->second);
    BOOST_TEST(1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('a' == c_rev_itr->first);
    BOOST_TEST('a' == c_rev_itr->second->key());
    BOOST_TEST(-2 == **c_rev_itr->second);
    BOOST_TEST(1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_p01.crend());
    BOOST_TEST(17 == atn_o00.size());
    BOOST_TEST(9 == atn_n01.size());
    BOOST_TEST(4 == atn_n02.size());
    BOOST_TEST(7 == atn_p01.size());
    atn_n01.swap(atn_p07);
    BOOST_TEST(0 == **atn_n01.parent());
    BOOST_TEST(0 == **atn_p07.parent());
    BOOST_TEST(-1 == **atn_o00.get('i'));
    BOOST_TEST(7 == **atn_o00.get('t'));
    c_fwd_itr = atn_n01.cbegin();
    BOOST_TEST('n' == c_fwd_itr->first);
    BOOST_TEST('n' == c_fwd_itr->second->key());
    BOOST_TEST(-3 == **c_fwd_itr->second);
    BOOST_TEST(-1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('s' == c_fwd_itr->first);
    BOOST_TEST('s' == c_fwd_itr->second->key());
    BOOST_TEST(11 == **c_fwd_itr->second);
    BOOST_TEST(-1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('t' == c_fwd_itr->first);
    BOOST_TEST('t' == c_fwd_itr->second->key());
    BOOST_TEST(12 == **c_fwd_itr->second);
    BOOST_TEST(-1 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_n01.cend());
    c_rev_itr = atn_n01.crbegin();
    BOOST_TEST('t' == c_rev_itr->first);
    BOOST_TEST('t' == c_rev_itr->second->key());
    BOOST_TEST(12 == **c_rev_itr->second);
    BOOST_TEST(-1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('s' == c_rev_itr->first);
    BOOST_TEST('s' == c_rev_itr->second->key());
    BOOST_TEST(11 == **c_rev_itr->second);
    BOOST_TEST(-1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('n' == c_rev_itr->first);
    BOOST_TEST('n' == c_rev_itr->second->key());
    BOOST_TEST(-3 == **c_rev_itr->second);
    BOOST_TEST(-1 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_n01.crend());
    c_fwd_itr = atn_p07.cbegin();
    BOOST_TEST('e' == c_fwd_itr->first);
    BOOST_TEST('e' == c_fwd_itr->second->key());
    BOOST_TEST(1 == **c_fwd_itr->second);
    BOOST_TEST(7 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('o' == c_fwd_itr->first);
    BOOST_TEST('o' == c_fwd_itr->second->key());
    BOOST_TEST(8 == **c_fwd_itr->second);
    BOOST_TEST(7 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_p07.cend());
    c_rev_itr = atn_p07.crbegin();
    BOOST_TEST('o' == c_rev_itr->first);
    BOOST_TEST('o' == c_rev_itr->second->key());
    BOOST_TEST(8 == **c_rev_itr->second);
    BOOST_TEST(7 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('e' == c_rev_itr->first);
    BOOST_TEST('e' == c_rev_itr->second->key());
    BOOST_TEST(1 == **c_rev_itr->second);
    BOOST_TEST(7 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_p07.crend());
    BOOST_TEST(17 == atn_o00.size());
    BOOST_TEST(3 == atn_n03.size());
    BOOST_TEST(6 == atn_n01.size());
    BOOST_TEST(9 == atn_p07.size());
    atn_o00.unset('t');
    c_fwd_itr = atn_o00.cbegin();
    BOOST_TEST('A' == c_fwd_itr->first);
    BOOST_TEST('A' == c_fwd_itr->second->key());
    BOOST_TEST(13 == **c_fwd_itr->second);
    BOOST_TEST(0 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST('i' == c_fwd_itr->first);
    BOOST_TEST('i' == c_fwd_itr->second->key());
    BOOST_TEST(-1 == **c_fwd_itr->second);
    BOOST_TEST(0 == **c_fwd_itr->second->parent());
    ++c_fwd_itr;
    BOOST_TEST(c_fwd_itr == atn_o00.cend());
    c_rev_itr = atn_o00.crbegin();
    BOOST_TEST('i' == c_rev_itr->first);
    BOOST_TEST('i' == c_rev_itr->second->key());
    BOOST_TEST(-1 == **c_rev_itr->second);
    BOOST_TEST(0 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST('A' == c_rev_itr->first);
    BOOST_TEST('A' == c_rev_itr->second->key());
    BOOST_TEST(13 == **c_rev_itr->second);
    BOOST_TEST(0 == **c_rev_itr->second->parent());
    ++c_rev_itr;
    BOOST_TEST(c_rev_itr == atn_o00.crend());
    BOOST_TEST(8 == atn_o00.size());
}

int main(int argc, char** argv)
{
    test_00();
    return ::boost::report_errors();
}

