// Copyright (C) 2025-2026 Cromwell D. Enage

#include <odds_and_ends/node/data.hpp>
#include <odds_and_ends/node/tree/base.hpp>
#include <odds_and_ends/node/tree/binary.hpp>
#include <odds_and_ends/composite_type/composite_type.hpp>
#include <boost/mpl/deque.hpp>
#include <boost/core/lightweight_test.hpp>

typedef ::odds_and_ends::composite_type::composite_type<
    ::boost::mpl::deque<
        ::odds_and_ends::node::data<int const>,
        ::odds_and_ends::node::tree::base<>,
        ::odds_and_ends::node::tree::binary<>
    >
> binary_tree_node;

void test_00()
{
    binary_tree_node btn_p09(9);
    binary_tree_node btn_p17(17);
    binary_tree_node btn_p23(23);
    binary_tree_node btn_p50(50);
    binary_tree_node btn_p76(76);

    BOOST_TEST(9 == *btn_p09);
    BOOST_TEST(17 == *btn_p17);
    BOOST_TEST(23 == *btn_p23);
    BOOST_TEST(50 == *btn_p50);
    BOOST_TEST(76 == *btn_p76);
    btn_p50.set_left(btn_p17);
    BOOST_TEST(17 == **btn_p50.begin());
    BOOST_TEST(50 == **btn_p50.begin()->parent());
    BOOST_TEST(btn_p50.begin() + 1 == btn_p50.end());
    BOOST_TEST(17 == **btn_p50.rbegin());
    BOOST_TEST(50 == **btn_p50.rbegin()->parent());
    BOOST_TEST(btn_p50.rbegin() + 1 == btn_p50.rend());
    btn_p50.set_right(btn_p76);
    BOOST_TEST(17 == **btn_p50.begin());
    BOOST_TEST(50 == **btn_p50.begin()->parent());
    BOOST_TEST(76 == **(btn_p50.begin() + 1));
    BOOST_TEST(50 == **(btn_p50.begin() + 1)->parent());
    BOOST_TEST(btn_p50.begin() + 2 == btn_p50.end());
    BOOST_TEST(76 == **btn_p50.rbegin());
    BOOST_TEST(50 == **btn_p50.rbegin()->parent());
    BOOST_TEST(17 == **(btn_p50.rbegin() + 1));
    BOOST_TEST(50 == **(btn_p50.rbegin() + 1)->parent());
    BOOST_TEST(btn_p50.rbegin() + 2 == btn_p50.rend());
    btn_p17.set_right(btn_p23);
    BOOST_TEST(23 == **btn_p17.begin());
    BOOST_TEST(17 == **btn_p17.begin()->parent());
    BOOST_TEST(btn_p17.begin() + 1 == btn_p17.end());
    BOOST_TEST(23 == **btn_p17.rbegin());
    BOOST_TEST(17 == **btn_p17.rbegin()->parent());
    BOOST_TEST(btn_p17.rbegin() + 1 == btn_p17.rend());
    btn_p17.set_left(btn_p09);
    BOOST_TEST(9 == **btn_p17.begin());
    BOOST_TEST(17 == **btn_p17.begin()->parent());
    BOOST_TEST(23 == **(btn_p17.begin() + 1));
    BOOST_TEST(17 == **(btn_p17.begin() + 1)->parent());
    BOOST_TEST(btn_p17.begin() + 2 == btn_p17.end());
    BOOST_TEST(23 == **btn_p17.rbegin());
    BOOST_TEST(17 == **btn_p17.rbegin()->parent());
    BOOST_TEST(9 == **(btn_p17.rbegin() + 1));
    BOOST_TEST(17 == **(btn_p17.rbegin() + 1)->parent());
    BOOST_TEST(btn_p17.rbegin() + 2 == btn_p17.rend());
    BOOST_TEST(!btn_p50.parent());
    BOOST_TEST(50 == **btn_p17.parent());
    BOOST_TEST(17 == **btn_p50.left());
    BOOST_TEST(50 == **btn_p76.parent());
    BOOST_TEST(76 == **btn_p50.right());
    BOOST_TEST(17 == **btn_p09.parent());
    BOOST_TEST(9 == **btn_p17.left());
    BOOST_TEST(17 == **btn_p23.parent());
    BOOST_TEST(23 == **btn_p17.right());
    BOOST_TEST(!btn_p09.left());
    BOOST_TEST(!btn_p09.right());
    BOOST_TEST(!btn_p23.left());
    BOOST_TEST(!btn_p23.right());
    BOOST_TEST(!btn_p76.left());
    BOOST_TEST(!btn_p76.right());

    binary_tree_node::traits::child_const_iterator fwd_itr = btn_p50.begin();

    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    --fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p50.begin());
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p50.end());
    fwd_itr = btn_p17.begin();
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    --fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p17.begin());
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p17.end());
    BOOST_TEST(btn_p09.begin() == btn_p09.end());
    BOOST_TEST(btn_p23.begin() == btn_p23.end());
    BOOST_TEST(btn_p76.begin() == btn_p76.end());

    binary_tree_node::traits::child_const_reverse_iterator rev_itr = btn_p50.rbegin();

    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    --rev_itr;
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p50.rbegin());
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p50.rend());
    rev_itr = btn_p17.rbegin();
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    --rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p17.rbegin());
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p17.rend());
    BOOST_TEST(btn_p09.rbegin() == btn_p09.rend());
    BOOST_TEST(btn_p23.rbegin() == btn_p23.rend());
    BOOST_TEST(btn_p76.rbegin() == btn_p76.rend());

    binary_tree_node::traits::pointer rotate_result = btn_p50.rotate_right();

    BOOST_TEST(17 == **rotate_result);
    BOOST_TEST(!btn_p17.parent());
    BOOST_TEST(17 == **btn_p09.parent());
    BOOST_TEST(9 == **btn_p17.left());
    BOOST_TEST(17 == **btn_p50.parent());
    BOOST_TEST(50 == **btn_p17.right());
    BOOST_TEST(50 == **btn_p23.parent());
    BOOST_TEST(23 == **btn_p50.left());
    BOOST_TEST(50 == **btn_p76.parent());
    BOOST_TEST(76 == **btn_p50.right());
    BOOST_TEST(!btn_p09.left());
    BOOST_TEST(!btn_p09.right());
    BOOST_TEST(!btn_p23.left());
    BOOST_TEST(!btn_p23.right());
    BOOST_TEST(!btn_p76.left());
    BOOST_TEST(!btn_p76.right());
    fwd_itr = btn_p17.begin();
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(50 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(50 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    --fwd_itr;
    BOOST_TEST(50 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p17.begin());
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p17.end());
    fwd_itr = btn_p50.begin();
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    --fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p50.begin());
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p50.end());
    BOOST_TEST(btn_p09.begin() == btn_p09.end());
    BOOST_TEST(btn_p23.begin() == btn_p23.end());
    BOOST_TEST(btn_p76.begin() == btn_p76.end());
    rev_itr = btn_p17.rbegin();
    BOOST_TEST(50 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(50 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    --rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p17.rbegin());
    BOOST_TEST(50 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p17.rend());
    rev_itr = btn_p50.rbegin();
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    --rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p50.rbegin());
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p50.rend());
    BOOST_TEST(btn_p09.rbegin() == btn_p09.rend());
    BOOST_TEST(btn_p23.rbegin() == btn_p23.rend());
    BOOST_TEST(btn_p76.rbegin() == btn_p76.rend());
    btn_p17.swap(btn_p50);
    BOOST_TEST(17 == **btn_p50.right());
    BOOST_TEST(50 == **btn_p17.parent());
    fwd_itr = btn_p17.begin();
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    --fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p17.begin());
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p17.end());
    rev_itr = btn_p17.rbegin();
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    --rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p17.rbegin());
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p17.rend());
    fwd_itr = btn_p50.begin();
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    --fwd_itr;
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p50.begin());
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p50.end());
    rev_itr = btn_p50.rbegin();
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    --rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p50.rbegin());
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p50.rend());
    btn_p17.swap(btn_p50);
    BOOST_TEST(50 == **btn_p17.right());
    BOOST_TEST(17 == **btn_p50.parent());
    fwd_itr = btn_p17.begin();
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(50 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(50 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    --fwd_itr;
    BOOST_TEST(50 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p17.begin());
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p17.end());
    rev_itr = btn_p17.rbegin();
    BOOST_TEST(50 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(50 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    --rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p17.rbegin());
    BOOST_TEST(50 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p17.rend());
    fwd_itr = btn_p50.begin();
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    --fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p50.begin());
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p50.end());
    rev_itr = btn_p50.rbegin();
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    --rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p50.rbegin());
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p50.rend());
    rotate_result = btn_p17.rotate_left();
    BOOST_TEST(50 == **rotate_result);
    BOOST_TEST(!btn_p50.parent());
    BOOST_TEST(50 == **btn_p17.parent());
    BOOST_TEST(17 == **btn_p50.left());
    BOOST_TEST(50 == **btn_p76.parent());
    BOOST_TEST(76 == **btn_p50.right());
    BOOST_TEST(17 == **btn_p09.parent());
    BOOST_TEST(9 == **btn_p17.left());
    BOOST_TEST(17 == **btn_p23.parent());
    BOOST_TEST(23 == **btn_p17.right());
    BOOST_TEST(!btn_p09.left());
    BOOST_TEST(!btn_p09.right());
    BOOST_TEST(!btn_p23.left());
    BOOST_TEST(!btn_p23.right());
    BOOST_TEST(!btn_p76.left());
    BOOST_TEST(!btn_p76.right());
    fwd_itr = btn_p50.begin();
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    --fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p50.begin());
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p50.end());
    fwd_itr = btn_p17.begin();
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    --fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p17.begin());
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p17.end());
    BOOST_TEST(btn_p09.begin() == btn_p09.end());
    BOOST_TEST(btn_p23.begin() == btn_p23.end());
    BOOST_TEST(btn_p76.begin() == btn_p76.end());
    rev_itr = btn_p50.rbegin();
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    --rev_itr;
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p50.rbegin());
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p50.rend());
    rev_itr = btn_p17.rbegin();
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    --rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p17.rbegin());
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p17.rend());
    BOOST_TEST(btn_p09.rbegin() == btn_p09.rend());
    BOOST_TEST(btn_p23.rbegin() == btn_p23.rend());
    BOOST_TEST(btn_p76.rbegin() == btn_p76.rend());
    btn_p50.swap(btn_p17);
    BOOST_TEST(50 == **btn_p17.left());
    BOOST_TEST(17 == **btn_p50.parent());
    fwd_itr = btn_p17.begin();
    BOOST_TEST(50 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(50 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    --fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p17.begin());
    BOOST_TEST(50 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p17.end());
    rev_itr = btn_p17.rbegin();
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(50 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(50 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    --rev_itr;
    BOOST_TEST(50 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p17.rbegin());
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p17.rend());
    fwd_itr = btn_p50.begin();
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    --fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p50.begin());
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p50.end());
    rev_itr = btn_p50.rbegin();
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    --rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p50.rbegin());
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p50.rend());
    btn_p50.swap(btn_p17);
    BOOST_TEST(17 == **btn_p50.left());
    BOOST_TEST(50 == **btn_p17.parent());
    fwd_itr = btn_p17.begin();
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    --fwd_itr;
    BOOST_TEST(23 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p17.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p17.begin());
    BOOST_TEST(9 == **fwd_itr);
    BOOST_TEST(17 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p17.end());
    rev_itr = btn_p17.rbegin();
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    --rev_itr;
    BOOST_TEST(9 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p17.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p17.rbegin());
    BOOST_TEST(23 == **rev_itr);
    BOOST_TEST(17 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p17.rend());
    fwd_itr = btn_p50.begin();
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    --fwd_itr;
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    --fwd_itr;
    BOOST_TEST(76 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    ++fwd_itr;
    BOOST_TEST(fwd_itr == btn_p50.end());
    fwd_itr -= 2;
    BOOST_TEST(fwd_itr == btn_p50.begin());
    BOOST_TEST(17 == **fwd_itr);
    BOOST_TEST(50 == **fwd_itr->parent());
    fwd_itr += 2;
    BOOST_TEST(fwd_itr == btn_p50.end());
    rev_itr = btn_p50.rbegin();
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    --rev_itr;
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    --rev_itr;
    BOOST_TEST(17 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    ++rev_itr;
    BOOST_TEST(rev_itr == btn_p50.rend());
    rev_itr -= 2;
    BOOST_TEST(rev_itr == btn_p50.rbegin());
    BOOST_TEST(76 == **rev_itr);
    BOOST_TEST(50 == **rev_itr->parent());
    rev_itr += 2;
    BOOST_TEST(rev_itr == btn_p50.rend());
}

void test_01()
{
    binary_tree_node btn_p01(1);
    binary_tree_node btn_p06(6);
    binary_tree_node btn_p08(8);
    binary_tree_node btn_p11(11);
    binary_tree_node btn_p13(13);
    binary_tree_node btn_p15(15);
    binary_tree_node btn_p17(17);
    binary_tree_node btn_p22(22);
    binary_tree_node btn_p25(25);
    binary_tree_node btn_p27(27);

    BOOST_TEST(1 == *btn_p01);
    BOOST_TEST(!btn_p01.parent());
    BOOST_TEST(!btn_p01.left());
    BOOST_TEST(!btn_p01.right());
    BOOST_TEST(btn_p01.begin() == btn_p01.end());
    BOOST_TEST(btn_p01.rbegin() == btn_p01.rend());
    BOOST_TEST(6 == *btn_p06);
    BOOST_TEST(!btn_p06.parent());
    BOOST_TEST(!btn_p06.left());
    BOOST_TEST(!btn_p06.right());
    BOOST_TEST(btn_p06.begin() == btn_p06.end());
    BOOST_TEST(btn_p06.rbegin() == btn_p06.rend());
    BOOST_TEST(8 == *btn_p08);
    BOOST_TEST(!btn_p08.parent());
    BOOST_TEST(!btn_p08.left());
    BOOST_TEST(!btn_p08.right());
    BOOST_TEST(btn_p08.begin() == btn_p08.end());
    BOOST_TEST(btn_p08.rbegin() == btn_p08.rend());
    BOOST_TEST(11 == *btn_p11);
    BOOST_TEST(!btn_p11.parent());
    BOOST_TEST(!btn_p11.left());
    BOOST_TEST(!btn_p11.right());
    BOOST_TEST(btn_p11.begin() == btn_p11.end());
    BOOST_TEST(btn_p11.rbegin() == btn_p11.rend());
    BOOST_TEST(13 == *btn_p13);
    BOOST_TEST(!btn_p13.parent());
    BOOST_TEST(!btn_p13.left());
    BOOST_TEST(!btn_p13.right());
    BOOST_TEST(btn_p13.begin() == btn_p13.end());
    BOOST_TEST(btn_p13.rbegin() == btn_p13.rend());
    BOOST_TEST(15 == *btn_p15);
    BOOST_TEST(!btn_p15.parent());
    BOOST_TEST(!btn_p15.left());
    BOOST_TEST(!btn_p15.right());
    BOOST_TEST(btn_p15.begin() == btn_p15.end());
    BOOST_TEST(btn_p15.rbegin() == btn_p15.rend());
    BOOST_TEST(17 == *btn_p17);
    BOOST_TEST(!btn_p17.parent());
    BOOST_TEST(!btn_p17.left());
    BOOST_TEST(!btn_p17.right());
    BOOST_TEST(btn_p17.begin() == btn_p17.end());
    BOOST_TEST(btn_p17.rbegin() == btn_p17.rend());
    BOOST_TEST(22 == *btn_p22);
    BOOST_TEST(!btn_p22.parent());
    BOOST_TEST(!btn_p22.left());
    BOOST_TEST(!btn_p22.right());
    BOOST_TEST(btn_p22.begin() == btn_p22.end());
    BOOST_TEST(btn_p22.rbegin() == btn_p22.rend());
    BOOST_TEST(25 == *btn_p25);
    BOOST_TEST(!btn_p25.parent());
    BOOST_TEST(!btn_p25.left());
    BOOST_TEST(!btn_p25.right());
    BOOST_TEST(btn_p25.begin() == btn_p25.end());
    BOOST_TEST(btn_p25.rbegin() == btn_p25.rend());
    BOOST_TEST(27 == *btn_p27);
    BOOST_TEST(!btn_p27.parent());
    BOOST_TEST(!btn_p27.left());
    BOOST_TEST(!btn_p27.right());
    BOOST_TEST(btn_p27.begin() == btn_p27.end());
    BOOST_TEST(btn_p27.rbegin() == btn_p27.rend());
    btn_p06.set_left(btn_p01);
    BOOST_TEST(6 == **btn_p01.parent());
    BOOST_TEST(1 == **btn_p06.left());
    BOOST_TEST(1 == **btn_p06.begin());
    BOOST_TEST(6 == **btn_p06.begin()->parent());
    BOOST_TEST(btn_p06.begin() + 1 == btn_p06.end());
    BOOST_TEST(1 == **btn_p06.rbegin());
    BOOST_TEST(6 == **btn_p06.rbegin()->parent());
    BOOST_TEST(btn_p06.rbegin() + 1 == btn_p06.rend());
    btn_p08.set_left(btn_p06);
    BOOST_TEST(8 == **btn_p06.parent());
    BOOST_TEST(6 == **btn_p08.left());
    BOOST_TEST(6 == **btn_p08.begin());
    BOOST_TEST(8 == **btn_p08.begin()->parent());
    BOOST_TEST(btn_p08.begin() + 1 == btn_p08.end());
    BOOST_TEST(6 == **btn_p08.rbegin());
    BOOST_TEST(8 == **btn_p08.rbegin()->parent());
    BOOST_TEST(btn_p08.rbegin() + 1 == btn_p08.rend());
    btn_p08.set_right(btn_p11);
    BOOST_TEST(8 == **btn_p11.parent());
    BOOST_TEST(11 == **btn_p08.right());
    BOOST_TEST(6 == **btn_p08.begin());
    BOOST_TEST(8 == **btn_p08.begin()->parent());
    BOOST_TEST(11 == **(btn_p08.begin() + 1));
    BOOST_TEST(8 == **(btn_p08.begin() + 1)->parent());
    BOOST_TEST(btn_p08.begin() + 2 == btn_p08.end());
    BOOST_TEST(11 == **btn_p08.rbegin());
    BOOST_TEST(8 == **btn_p08.rbegin()->parent());
    BOOST_TEST(6 == **(btn_p08.rbegin() + 1));
    BOOST_TEST(8 == **(btn_p08.rbegin() + 1)->parent());
    BOOST_TEST(btn_p08.rbegin() + 2 == btn_p08.rend());
    btn_p13.set_left(btn_p08);
    BOOST_TEST(13 == **btn_p08.parent());
    BOOST_TEST(8 == **btn_p13.left());
    BOOST_TEST(8 == **btn_p13.begin());
    BOOST_TEST(13 == **btn_p13.begin()->parent());
    BOOST_TEST(btn_p13.begin() + 1 == btn_p13.end());
    BOOST_TEST(8 == **btn_p13.rbegin());
    BOOST_TEST(13 == **btn_p13.rbegin()->parent());
    BOOST_TEST(btn_p13.rbegin() + 1 == btn_p13.rend());
    btn_p13.set_right(btn_p17);
    BOOST_TEST(13 == **btn_p17.parent());
    BOOST_TEST(17 == **btn_p13.right());
    BOOST_TEST(8 == **btn_p13.begin());
    BOOST_TEST(13 == **btn_p13.begin()->parent());
    BOOST_TEST(17 == **(btn_p13.begin() + 1));
    BOOST_TEST(13 == **(btn_p13.begin() + 1)->parent());
    BOOST_TEST(btn_p13.begin() + 2 == btn_p13.end());
    BOOST_TEST(17 == **btn_p13.rbegin());
    BOOST_TEST(13 == **btn_p13.rbegin()->parent());
    BOOST_TEST(8 == **(btn_p13.rbegin() + 1));
    BOOST_TEST(13 == **(btn_p13.rbegin() + 1)->parent());
    BOOST_TEST(btn_p13.rbegin() + 2 == btn_p13.rend());
    btn_p17.set_left(btn_p15);
    BOOST_TEST(17 == **btn_p15.parent());
    BOOST_TEST(15 == **btn_p17.left());
    BOOST_TEST(15 == **btn_p17.begin());
    BOOST_TEST(17 == **btn_p17.begin()->parent());
    BOOST_TEST(btn_p17.begin() + 1 == btn_p17.end());
    BOOST_TEST(15 == **btn_p17.rbegin());
    BOOST_TEST(17 == **btn_p17.rbegin()->parent());
    BOOST_TEST(btn_p17.rbegin() + 1 == btn_p17.rend());
    btn_p17.set_right(btn_p25);
    BOOST_TEST(17 == **btn_p25.parent());
    BOOST_TEST(25 == **btn_p17.right());
    BOOST_TEST(15 == **btn_p17.begin());
    BOOST_TEST(17 == **btn_p17.begin()->parent());
    BOOST_TEST(25 == **(btn_p17.begin() + 1));
    BOOST_TEST(17 == **(btn_p17.begin() + 1)->parent());
    BOOST_TEST(btn_p17.begin() + 2 == btn_p17.end());
    BOOST_TEST(25 == **btn_p17.rbegin());
    BOOST_TEST(17 == **btn_p17.rbegin()->parent());
    BOOST_TEST(15 == **(btn_p17.rbegin() + 1));
    BOOST_TEST(17 == **(btn_p17.rbegin() + 1)->parent());
    BOOST_TEST(btn_p17.rbegin() + 2 == btn_p17.rend());
    btn_p25.set_left(btn_p22);
    BOOST_TEST(25 == **btn_p22.parent());
    BOOST_TEST(22 == **btn_p25.left());
    BOOST_TEST(22 == **btn_p25.begin());
    BOOST_TEST(25 == **btn_p25.begin()->parent());
    BOOST_TEST(btn_p25.begin() + 1 == btn_p25.end());
    BOOST_TEST(22 == **btn_p25.rbegin());
    BOOST_TEST(25 == **btn_p25.rbegin()->parent());
    BOOST_TEST(btn_p25.rbegin() + 1 == btn_p25.rend());
    btn_p25.set_right(btn_p27);
    BOOST_TEST(25 == **btn_p27.parent());
    BOOST_TEST(27 == **btn_p25.right());
    BOOST_TEST(22 == **btn_p25.begin());
    BOOST_TEST(25 == **btn_p25.begin()->parent());
    BOOST_TEST(27 == **(btn_p25.begin() + 1));
    BOOST_TEST(25 == **(btn_p25.begin() + 1)->parent());
    BOOST_TEST(btn_p25.begin() + 2 == btn_p25.end());
    BOOST_TEST(27 == **btn_p25.rbegin());
    BOOST_TEST(25 == **btn_p25.rbegin()->parent());
    BOOST_TEST(22 == **(btn_p25.rbegin() + 1));
    BOOST_TEST(25 == **(btn_p25.rbegin() + 1)->parent());
    BOOST_TEST(btn_p25.rbegin() + 2 == btn_p25.rend());
    btn_p17.swap(btn_p25);
    BOOST_TEST(25 == **btn_p13.right());
    BOOST_TEST(25 == **btn_p17.parent());
    BOOST_TEST(22 == **btn_p17.left());
    BOOST_TEST(27 == **btn_p17.right());
    BOOST_TEST(13 == **btn_p25.parent());
    BOOST_TEST(15 == **btn_p25.left());
    BOOST_TEST(17 == **btn_p25.right());
    BOOST_TEST(15 == **btn_p25.begin());
    BOOST_TEST(25 == **btn_p25.begin()->parent());
    BOOST_TEST(22 == **btn_p17.begin());
    BOOST_TEST(17 == **btn_p17.begin()->parent());
    BOOST_TEST(27 == **(btn_p17.begin() + 1));
    BOOST_TEST(17 == **(btn_p17.begin() + 1)->parent());
    BOOST_TEST(btn_p17.begin() + 2 == btn_p17.end());
    BOOST_TEST(27 == **btn_p17.rbegin());
    BOOST_TEST(17 == **btn_p17.rbegin()->parent());
    BOOST_TEST(22 == **(btn_p17.rbegin() + 1));
    BOOST_TEST(17 == **(btn_p17.rbegin() + 1)->parent());
    BOOST_TEST(btn_p17.rbegin() + 2 == btn_p17.rend());
    BOOST_TEST(17 == **(btn_p25.begin() + 1));
    BOOST_TEST(25 == **(btn_p25.begin() + 1)->parent());
    BOOST_TEST(btn_p25.begin() + 2 == btn_p25.end());
    BOOST_TEST(17 == **btn_p25.rbegin());
    BOOST_TEST(25 == **btn_p25.rbegin()->parent());
    BOOST_TEST(15 == **(btn_p25.rbegin() + 1));
    BOOST_TEST(25 == **(btn_p25.rbegin() + 1)->parent());
    BOOST_TEST(btn_p25.rbegin() + 2 == btn_p25.rend());
    btn_p17.swap(btn_p25);
    BOOST_TEST(17 == **btn_p13.right());
    BOOST_TEST(13 == **btn_p17.parent());
    BOOST_TEST(15 == **btn_p17.left());
    BOOST_TEST(25 == **btn_p17.right());
    BOOST_TEST(17 == **btn_p25.parent());
    BOOST_TEST(22 == **btn_p25.left());
    BOOST_TEST(27 == **btn_p25.right());
    BOOST_TEST(15 == **btn_p17.begin());
    BOOST_TEST(17 == **btn_p17.begin()->parent());
    BOOST_TEST(25 == **(btn_p17.begin() + 1));
    BOOST_TEST(17 == **(btn_p17.begin() + 1)->parent());
    BOOST_TEST(btn_p17.begin() + 2 == btn_p17.end());
    BOOST_TEST(25 == **btn_p17.rbegin());
    BOOST_TEST(17 == **btn_p17.rbegin()->parent());
    BOOST_TEST(15 == **(btn_p17.rbegin() + 1));
    BOOST_TEST(17 == **(btn_p17.rbegin() + 1)->parent());
    BOOST_TEST(btn_p17.rbegin() + 2 == btn_p17.rend());
    BOOST_TEST(22 == **btn_p25.begin());
    BOOST_TEST(25 == **btn_p25.begin()->parent());
    BOOST_TEST(27 == **(btn_p25.begin() + 1));
    BOOST_TEST(25 == **(btn_p25.begin() + 1)->parent());
    BOOST_TEST(btn_p25.begin() + 2 == btn_p25.end());
    BOOST_TEST(27 == **btn_p25.rbegin());
    BOOST_TEST(25 == **btn_p25.rbegin()->parent());
    BOOST_TEST(22 == **(btn_p25.rbegin() + 1));
    BOOST_TEST(25 == **(btn_p25.rbegin() + 1)->parent());
    BOOST_TEST(btn_p25.rbegin() + 2 == btn_p25.rend());

    binary_tree_node::traits::pointer rotate_result = btn_p08.rotate_right();

    BOOST_TEST(6 == **rotate_result);
    BOOST_TEST(6 == **btn_p01.parent());
    BOOST_TEST(!btn_p01.left());
    BOOST_TEST(!btn_p01.right());
    BOOST_TEST(btn_p01.begin() == btn_p01.end());
    BOOST_TEST(btn_p01.rbegin() == btn_p01.rend());
    BOOST_TEST(13 == **btn_p06.parent());
    BOOST_TEST(1 == **btn_p06.left());
    BOOST_TEST(8 == **btn_p06.right());
    BOOST_TEST(1 == **btn_p06.begin());
    BOOST_TEST(8 == **(btn_p06.begin() + 1));
    BOOST_TEST(btn_p06.begin() + 2 == btn_p06.end());
    BOOST_TEST(8 == **btn_p06.rbegin());
    BOOST_TEST(1 == **(btn_p06.rbegin() + 1));
    BOOST_TEST(btn_p06.rbegin() + 2 == btn_p06.rend());
    BOOST_TEST(6 == **btn_p08.parent());
    BOOST_TEST(!btn_p08.left());
    BOOST_TEST(11 == **btn_p08.right());
    BOOST_TEST(11 == **btn_p08.begin());
    BOOST_TEST(btn_p08.begin() + 1 == btn_p08.end());
    BOOST_TEST(11 == **btn_p08.rbegin());
    BOOST_TEST(btn_p08.rbegin() + 1 == btn_p08.rend());
    BOOST_TEST(8 == **btn_p11.parent());
    BOOST_TEST(!btn_p11.left());
    BOOST_TEST(!btn_p11.right());
    BOOST_TEST(btn_p11.begin() == btn_p11.end());
    BOOST_TEST(btn_p11.rbegin() == btn_p11.rend());
    BOOST_TEST(!btn_p13.parent());
    BOOST_TEST(6 == **btn_p13.left());
    BOOST_TEST(17 == **btn_p13.right());
    BOOST_TEST(6 == **btn_p13.begin());
    BOOST_TEST(17 == **(btn_p13.begin() + 1));
    BOOST_TEST(btn_p13.begin() + 2 == btn_p13.end());
    BOOST_TEST(17 == **btn_p13.rbegin());
    BOOST_TEST(6 == **(btn_p13.rbegin() + 1));
    BOOST_TEST(btn_p13.rbegin() + 2 == btn_p13.rend());
    BOOST_TEST(17 == **btn_p15.parent());
    BOOST_TEST(!btn_p15.left());
    BOOST_TEST(!btn_p15.right());
    BOOST_TEST(btn_p15.begin() == btn_p15.end());
    BOOST_TEST(btn_p15.rbegin() == btn_p15.rend());
    BOOST_TEST(13 == **btn_p17.parent());
    BOOST_TEST(15 == **btn_p17.left());
    BOOST_TEST(25 == **btn_p17.right());
    BOOST_TEST(15 == **btn_p17.begin());
    BOOST_TEST(25 == **(btn_p17.begin() + 1));
    BOOST_TEST(btn_p17.begin() + 2 == btn_p17.end());
    BOOST_TEST(25 == **btn_p17.rbegin());
    BOOST_TEST(15 == **(btn_p17.rbegin() + 1));
    BOOST_TEST(btn_p17.rbegin() + 2 == btn_p17.rend());
    BOOST_TEST(25 == **btn_p22.parent());
    BOOST_TEST(!btn_p22.left());
    BOOST_TEST(!btn_p22.right());
    BOOST_TEST(btn_p22.begin() == btn_p22.end());
    BOOST_TEST(btn_p22.rbegin() == btn_p22.rend());
    BOOST_TEST(17 == **btn_p25.parent());
    BOOST_TEST(22 == **btn_p25.left());
    BOOST_TEST(27 == **btn_p25.right());
    BOOST_TEST(22 == **btn_p25.begin());
    BOOST_TEST(27 == **(btn_p25.begin() + 1));
    BOOST_TEST(btn_p25.begin() + 2 == btn_p25.end());
    BOOST_TEST(27 == **btn_p25.rbegin());
    BOOST_TEST(22 == **(btn_p25.rbegin() + 1));
    BOOST_TEST(btn_p25.rbegin() + 2 == btn_p25.rend());
    BOOST_TEST(25 == **btn_p27.parent());
    BOOST_TEST(!btn_p27.left());
    BOOST_TEST(!btn_p27.right());
    BOOST_TEST(btn_p27.begin() == btn_p27.end());
    BOOST_TEST(btn_p27.rbegin() == btn_p27.rend());
    rotate_result = btn_p17.rotate_left();
    BOOST_TEST(25 == **rotate_result);
    BOOST_TEST(6 == **btn_p01.parent());
    BOOST_TEST(!btn_p01.left());
    BOOST_TEST(!btn_p01.right());
    BOOST_TEST(btn_p01.begin() == btn_p01.end());
    BOOST_TEST(btn_p01.rbegin() == btn_p01.rend());
    BOOST_TEST(13 == **btn_p06.parent());
    BOOST_TEST(1 == **btn_p06.left());
    BOOST_TEST(8 == **btn_p06.right());
    BOOST_TEST(1 == **btn_p06.begin());
    BOOST_TEST(8 == **(btn_p06.begin() + 1));
    BOOST_TEST(btn_p06.begin() + 2 == btn_p06.end());
    BOOST_TEST(8 == **btn_p06.rbegin());
    BOOST_TEST(1 == **(btn_p06.rbegin() + 1));
    BOOST_TEST(btn_p06.rbegin() + 2 == btn_p06.rend());
    BOOST_TEST(6 == **btn_p08.parent());
    BOOST_TEST(!btn_p08.left());
    BOOST_TEST(11 == **btn_p08.right());
    BOOST_TEST(11 == **btn_p08.begin());
    BOOST_TEST(btn_p08.begin() + 1 == btn_p08.end());
    BOOST_TEST(11 == **btn_p08.rbegin());
    BOOST_TEST(btn_p08.rbegin() + 1 == btn_p08.rend());
    BOOST_TEST(8 == **btn_p11.parent());
    BOOST_TEST(!btn_p11.left());
    BOOST_TEST(!btn_p11.right());
    BOOST_TEST(btn_p11.begin() == btn_p11.end());
    BOOST_TEST(btn_p11.rbegin() == btn_p11.rend());
    BOOST_TEST(!btn_p13.parent());
    BOOST_TEST(6 == **btn_p13.left());
    BOOST_TEST(25 == **btn_p13.right());
    BOOST_TEST(6 == **btn_p13.begin());
    BOOST_TEST(25 == **(btn_p13.begin() + 1));
    BOOST_TEST(btn_p13.begin() + 2 == btn_p13.end());
    BOOST_TEST(25 == **btn_p13.rbegin());
    BOOST_TEST(6 == **(btn_p13.rbegin() + 1));
    BOOST_TEST(btn_p13.rbegin() + 2 == btn_p13.rend());
    BOOST_TEST(17 == **btn_p15.parent());
    BOOST_TEST(!btn_p15.left());
    BOOST_TEST(!btn_p15.right());
    BOOST_TEST(btn_p15.begin() == btn_p15.end());
    BOOST_TEST(btn_p15.rbegin() == btn_p15.rend());
    BOOST_TEST(25 == **btn_p17.parent());
    BOOST_TEST(15 == **btn_p17.left());
    BOOST_TEST(22 == **btn_p17.right());
    BOOST_TEST(15 == **btn_p17.begin());
    BOOST_TEST(22 == **(btn_p17.begin() + 1));
    BOOST_TEST(btn_p17.begin() + 2 == btn_p17.end());
    BOOST_TEST(22 == **btn_p17.rbegin());
    BOOST_TEST(15 == **(btn_p17.rbegin() + 1));
    BOOST_TEST(btn_p17.rbegin() + 2 == btn_p17.rend());
    BOOST_TEST(17 == **btn_p22.parent());
    BOOST_TEST(!btn_p22.left());
    BOOST_TEST(!btn_p22.right());
    BOOST_TEST(btn_p22.begin() == btn_p22.end());
    BOOST_TEST(btn_p22.rbegin() == btn_p22.rend());
    BOOST_TEST(13 == **btn_p25.parent());
    BOOST_TEST(17 == **btn_p25.left());
    BOOST_TEST(27 == **btn_p25.right());
    BOOST_TEST(17 == **btn_p25.begin());
    BOOST_TEST(27 == **(btn_p25.begin() + 1));
    BOOST_TEST(btn_p25.begin() + 2 == btn_p25.end());
    BOOST_TEST(27 == **btn_p25.rbegin());
    BOOST_TEST(17 == **(btn_p25.rbegin() + 1));
    BOOST_TEST(btn_p25.rbegin() + 2 == btn_p25.rend());
    BOOST_TEST(25 == **btn_p27.parent());
    BOOST_TEST(!btn_p27.left());
    BOOST_TEST(!btn_p27.right());
    BOOST_TEST(btn_p27.begin() == btn_p27.end());
    BOOST_TEST(btn_p27.rbegin() == btn_p27.rend());
    btn_p25.swap(btn_p17);
    BOOST_TEST(17 == **btn_p13.right());
    BOOST_TEST(17 == **btn_p25.parent());
    BOOST_TEST(15 == **btn_p25.left());
    BOOST_TEST(22 == **btn_p25.right());
    BOOST_TEST(13 == **btn_p17.parent());
    BOOST_TEST(25 == **btn_p17.left());
    BOOST_TEST(27 == **btn_p17.right());
    BOOST_TEST(25 == **btn_p17.begin());
    BOOST_TEST(17 == **btn_p17.begin()->parent());
    BOOST_TEST(27 == **(btn_p17.begin() + 1));
    BOOST_TEST(17 == **(btn_p17.begin() + 1)->parent());
    BOOST_TEST(btn_p17.begin() + 2 == btn_p17.end());
    BOOST_TEST(27 == **btn_p17.rbegin());
    BOOST_TEST(17 == **btn_p17.rbegin()->parent());
    BOOST_TEST(25 == **(btn_p17.rbegin() + 1));
    BOOST_TEST(17 == **(btn_p17.rbegin() + 1)->parent());
    BOOST_TEST(btn_p17.rbegin() + 2 == btn_p17.rend());
    BOOST_TEST(15 == **btn_p25.begin());
    BOOST_TEST(25 == **btn_p25.begin()->parent());
    BOOST_TEST(22 == **(btn_p25.begin() + 1));
    BOOST_TEST(25 == **(btn_p25.begin() + 1)->parent());
    BOOST_TEST(btn_p25.begin() + 2 == btn_p25.end());
    BOOST_TEST(22 == **btn_p25.rbegin());
    BOOST_TEST(25 == **btn_p25.rbegin()->parent());
    BOOST_TEST(15 == **(btn_p25.rbegin() + 1));
    BOOST_TEST(25 == **(btn_p25.rbegin() + 1)->parent());
    BOOST_TEST(btn_p25.rbegin() + 2 == btn_p25.rend());
    btn_p25.swap(btn_p17);
    BOOST_TEST(25 == **btn_p13.right());
    BOOST_TEST(25 == **btn_p17.parent());
    BOOST_TEST(15 == **btn_p17.left());
    BOOST_TEST(22 == **btn_p17.right());
    BOOST_TEST(13 == **btn_p25.parent());
    BOOST_TEST(17 == **btn_p25.left());
    BOOST_TEST(27 == **btn_p25.right());
    BOOST_TEST(15 == **btn_p17.begin());
    BOOST_TEST(17 == **btn_p17.begin()->parent());
    BOOST_TEST(22 == **(btn_p17.begin() + 1));
    BOOST_TEST(17 == **(btn_p17.begin() + 1)->parent());
    BOOST_TEST(btn_p17.begin() + 2 == btn_p17.end());
    BOOST_TEST(22 == **btn_p17.rbegin());
    BOOST_TEST(17 == **btn_p17.rbegin()->parent());
    BOOST_TEST(15 == **(btn_p17.rbegin() + 1));
    BOOST_TEST(17 == **(btn_p17.rbegin() + 1)->parent());
    BOOST_TEST(btn_p17.rbegin() + 2 == btn_p17.rend());
    BOOST_TEST(17 == **btn_p25.begin());
    BOOST_TEST(25 == **btn_p25.begin()->parent());
    BOOST_TEST(27 == **(btn_p25.begin() + 1));
    BOOST_TEST(25 == **(btn_p25.begin() + 1)->parent());
    BOOST_TEST(btn_p25.begin() + 2 == btn_p25.end());
    BOOST_TEST(27 == **btn_p25.rbegin());
    BOOST_TEST(25 == **btn_p25.rbegin()->parent());
    BOOST_TEST(17 == **(btn_p25.rbegin() + 1));
    BOOST_TEST(25 == **(btn_p25.rbegin() + 1)->parent());
    BOOST_TEST(btn_p25.rbegin() + 2 == btn_p25.rend());
    rotate_result = btn_p06.rotate_left();
    BOOST_TEST(8 == **rotate_result);
    BOOST_TEST(6 == **btn_p01.parent());
    BOOST_TEST(btn_p01.begin() == btn_p01.end());
    BOOST_TEST(btn_p01.rbegin() == btn_p01.rend());
    BOOST_TEST(8 == **btn_p06.parent());
    BOOST_TEST(1 == **btn_p06.left());
    BOOST_TEST(1 == **btn_p06.begin());
    BOOST_TEST(btn_p06.begin() + 1 == btn_p06.end());
    BOOST_TEST(1 == **btn_p06.rbegin());
    BOOST_TEST(btn_p06.rbegin() + 1 == btn_p06.rend());
    BOOST_TEST(13 == **btn_p08.parent());
    BOOST_TEST(11 == **btn_p08.right());
    BOOST_TEST(6 == **btn_p08.begin());
    BOOST_TEST(11 == **(btn_p08.begin() + 1));
    BOOST_TEST(btn_p08.begin() + 2 == btn_p08.end());
    BOOST_TEST(11 == **btn_p08.rbegin());
    BOOST_TEST(6 == **(btn_p08.rbegin() + 1));
    BOOST_TEST(btn_p08.rbegin() + 2 == btn_p08.rend());
    BOOST_TEST(8 == **btn_p11.parent());
    BOOST_TEST(!btn_p11.left());
    BOOST_TEST(!btn_p11.right());
    BOOST_TEST(btn_p11.begin() == btn_p11.end());
    BOOST_TEST(btn_p11.rbegin() == btn_p11.rend());
    BOOST_TEST(!btn_p13.parent());
    BOOST_TEST(8 == **btn_p13.left());
    BOOST_TEST(25 == **btn_p13.right());
    BOOST_TEST(8 == **btn_p13.begin());
    BOOST_TEST(25 == **(btn_p13.begin() + 1));
    BOOST_TEST(btn_p13.begin() + 2 == btn_p13.end());
    BOOST_TEST(25 == **btn_p13.rbegin());
    BOOST_TEST(8 == **(btn_p13.rbegin() + 1));
    BOOST_TEST(btn_p13.rbegin() + 2 == btn_p13.rend());
    BOOST_TEST(17 == **btn_p15.parent());
    BOOST_TEST(!btn_p15.left());
    BOOST_TEST(!btn_p15.right());
    BOOST_TEST(btn_p15.begin() == btn_p15.end());
    BOOST_TEST(btn_p15.rbegin() == btn_p15.rend());
    BOOST_TEST(25 == **btn_p17.parent());
    BOOST_TEST(15 == **btn_p17.left());
    BOOST_TEST(22 == **btn_p17.right());
    BOOST_TEST(15 == **btn_p17.begin());
    BOOST_TEST(22 == **(btn_p17.begin() + 1));
    BOOST_TEST(btn_p17.begin() + 2 == btn_p17.end());
    BOOST_TEST(22 == **btn_p17.rbegin());
    BOOST_TEST(15 == **(btn_p17.rbegin() + 1));
    BOOST_TEST(btn_p17.rbegin() + 2 == btn_p17.rend());
    BOOST_TEST(17 == **btn_p22.parent());
    BOOST_TEST(!btn_p22.left());
    BOOST_TEST(!btn_p22.right());
    BOOST_TEST(btn_p22.begin() == btn_p22.end());
    BOOST_TEST(btn_p22.rbegin() == btn_p22.rend());
    BOOST_TEST(13 == **btn_p25.parent());
    BOOST_TEST(17 == **btn_p25.left());
    BOOST_TEST(27 == **btn_p25.right());
    BOOST_TEST(17 == **btn_p25.begin());
    BOOST_TEST(27 == **(btn_p25.begin() + 1));
    BOOST_TEST(btn_p25.begin() + 2 == btn_p25.end());
    BOOST_TEST(27 == **btn_p25.rbegin());
    BOOST_TEST(17 == **(btn_p25.rbegin() + 1));
    BOOST_TEST(btn_p25.rbegin() + 2 == btn_p25.rend());
    BOOST_TEST(25 == **btn_p27.parent());
    BOOST_TEST(!btn_p27.left());
    BOOST_TEST(!btn_p27.right());
    BOOST_TEST(btn_p27.begin() == btn_p27.end());
    BOOST_TEST(btn_p27.rbegin() == btn_p27.rend());
    rotate_result = btn_p25.rotate_right();
    BOOST_TEST(17 == **rotate_result);
    BOOST_TEST(6 == **btn_p01.parent());
    BOOST_TEST(btn_p01.begin() == btn_p01.end());
    BOOST_TEST(btn_p01.rbegin() == btn_p01.rend());
    BOOST_TEST(8 == **btn_p06.parent());
    BOOST_TEST(1 == **btn_p06.left());
    BOOST_TEST(1 == **btn_p06.begin());
    BOOST_TEST(btn_p06.begin() + 1 == btn_p06.end());
    BOOST_TEST(1 == **btn_p06.rbegin());
    BOOST_TEST(btn_p06.rbegin() + 1 == btn_p06.rend());
    BOOST_TEST(13 == **btn_p08.parent());
    BOOST_TEST(11 == **btn_p08.right());
    BOOST_TEST(6 == **btn_p08.begin());
    BOOST_TEST(11 == **(btn_p08.begin() + 1));
    BOOST_TEST(btn_p08.begin() + 2 == btn_p08.end());
    BOOST_TEST(11 == **btn_p08.rbegin());
    BOOST_TEST(6 == **(btn_p08.rbegin() + 1));
    BOOST_TEST(btn_p08.rbegin() + 2 == btn_p08.rend());
    BOOST_TEST(8 == **btn_p11.parent());
    BOOST_TEST(!btn_p11.left());
    BOOST_TEST(!btn_p11.right());
    BOOST_TEST(btn_p11.begin() == btn_p11.end());
    BOOST_TEST(btn_p11.rbegin() == btn_p11.rend());
    BOOST_TEST(!btn_p13.parent());
    BOOST_TEST(8 == **btn_p13.left());
    BOOST_TEST(17 == **btn_p13.right());
    BOOST_TEST(8 == **btn_p13.begin());
    BOOST_TEST(17 == **(btn_p13.begin() + 1));
    BOOST_TEST(btn_p13.begin() + 2 == btn_p13.end());
    BOOST_TEST(17 == **btn_p13.rbegin());
    BOOST_TEST(8 == **(btn_p13.rbegin() + 1));
    BOOST_TEST(btn_p13.rbegin() + 2 == btn_p13.rend());
    BOOST_TEST(17 == **btn_p15.parent());
    BOOST_TEST(!btn_p15.left());
    BOOST_TEST(!btn_p15.right());
    BOOST_TEST(btn_p15.begin() == btn_p15.end());
    BOOST_TEST(btn_p15.rbegin() == btn_p15.rend());
    BOOST_TEST(13 == **btn_p17.parent());
    BOOST_TEST(15 == **btn_p17.left());
    BOOST_TEST(25 == **btn_p17.right());
    BOOST_TEST(15 == **btn_p17.begin());
    BOOST_TEST(25 == **(btn_p17.begin() + 1));
    BOOST_TEST(btn_p17.begin() + 2 == btn_p17.end());
    BOOST_TEST(25 == **btn_p17.rbegin());
    BOOST_TEST(15 == **(btn_p17.rbegin() + 1));
    BOOST_TEST(btn_p17.rbegin() + 2 == btn_p17.rend());
    BOOST_TEST(25 == **btn_p22.parent());
    BOOST_TEST(!btn_p22.left());
    BOOST_TEST(!btn_p22.right());
    BOOST_TEST(btn_p22.begin() == btn_p22.end());
    BOOST_TEST(btn_p22.rbegin() == btn_p22.rend());
    BOOST_TEST(17 == **btn_p25.parent());
    BOOST_TEST(22 == **btn_p25.left());
    BOOST_TEST(27 == **btn_p25.right());
    BOOST_TEST(22 == **btn_p25.begin());
    BOOST_TEST(27 == **(btn_p25.begin() + 1));
    BOOST_TEST(btn_p25.begin() + 2 == btn_p25.end());
    BOOST_TEST(27 == **btn_p25.rbegin());
    BOOST_TEST(22 == **(btn_p25.rbegin() + 1));
    BOOST_TEST(btn_p25.rbegin() + 2 == btn_p25.rend());
    BOOST_TEST(25 == **btn_p27.parent());
    BOOST_TEST(!btn_p27.left());
    BOOST_TEST(!btn_p27.right());
    BOOST_TEST(btn_p27.begin() == btn_p27.end());
    BOOST_TEST(btn_p27.rbegin() == btn_p27.rend());
    btn_p17.unset_right();
    BOOST_TEST(6 == **btn_p01.parent());
    BOOST_TEST(btn_p01.begin() == btn_p01.end());
    BOOST_TEST(btn_p01.rbegin() == btn_p01.rend());
    BOOST_TEST(8 == **btn_p06.parent());
    BOOST_TEST(1 == **btn_p06.left());
    BOOST_TEST(1 == **btn_p06.begin());
    BOOST_TEST(btn_p06.begin() + 1 == btn_p06.end());
    BOOST_TEST(1 == **btn_p06.rbegin());
    BOOST_TEST(btn_p06.rbegin() + 1 == btn_p06.rend());
    BOOST_TEST(13 == **btn_p08.parent());
    BOOST_TEST(11 == **btn_p08.right());
    BOOST_TEST(6 == **btn_p08.begin());
    BOOST_TEST(11 == **(btn_p08.begin() + 1));
    BOOST_TEST(btn_p08.begin() + 2 == btn_p08.end());
    BOOST_TEST(11 == **btn_p08.rbegin());
    BOOST_TEST(6 == **(btn_p08.rbegin() + 1));
    BOOST_TEST(btn_p08.rbegin() + 2 == btn_p08.rend());
    BOOST_TEST(8 == **btn_p11.parent());
    BOOST_TEST(!btn_p11.left());
    BOOST_TEST(!btn_p11.right());
    BOOST_TEST(btn_p11.begin() == btn_p11.end());
    BOOST_TEST(btn_p11.rbegin() == btn_p11.rend());
    BOOST_TEST(!btn_p13.parent());
    BOOST_TEST(8 == **btn_p13.left());
    BOOST_TEST(17 == **btn_p13.right());
    BOOST_TEST(8 == **btn_p13.begin());
    BOOST_TEST(17 == **(btn_p13.begin() + 1));
    BOOST_TEST(btn_p13.begin() + 2 == btn_p13.end());
    BOOST_TEST(17 == **btn_p13.rbegin());
    BOOST_TEST(8 == **(btn_p13.rbegin() + 1));
    BOOST_TEST(btn_p13.rbegin() + 2 == btn_p13.rend());
    BOOST_TEST(17 == **btn_p15.parent());
    BOOST_TEST(!btn_p15.left());
    BOOST_TEST(!btn_p15.right());
    BOOST_TEST(btn_p15.begin() == btn_p15.end());
    BOOST_TEST(btn_p15.rbegin() == btn_p15.rend());
    BOOST_TEST(13 == **btn_p17.parent());
    BOOST_TEST(15 == **btn_p17.left());
    BOOST_TEST(15 == **btn_p17.begin());
    BOOST_TEST(btn_p17.begin() + 1 == btn_p17.end());
    btn_p08.clear();
    BOOST_TEST(!btn_p08.left());
    BOOST_TEST(!btn_p08.right());
    BOOST_TEST(btn_p08.rbegin() == btn_p08.rend());
    BOOST_TEST(13 == **btn_p08.parent());
    BOOST_TEST(!btn_p13.parent());
    BOOST_TEST(8 == **btn_p13.left());
    BOOST_TEST(17 == **btn_p13.right());
    BOOST_TEST(8 == **btn_p13.begin());
    BOOST_TEST(17 == **(btn_p13.begin() + 1));
    BOOST_TEST(btn_p13.begin() + 2 == btn_p13.end());
    BOOST_TEST(17 == **btn_p13.rbegin());
    BOOST_TEST(8 == **(btn_p13.rbegin() + 1));
    BOOST_TEST(btn_p13.rbegin() + 2 == btn_p13.rend());
    BOOST_TEST(17 == **btn_p15.parent());
    BOOST_TEST(!btn_p15.left());
    BOOST_TEST(!btn_p15.right());
    BOOST_TEST(btn_p15.begin() == btn_p15.end());
    BOOST_TEST(btn_p15.rbegin() == btn_p15.rend());
    BOOST_TEST(13 == **btn_p17.parent());
    BOOST_TEST(15 == **btn_p17.left());
    BOOST_TEST(15 == **btn_p17.begin());
    BOOST_TEST(btn_p17.begin() + 1 == btn_p17.end());
}

int main(int argc, char** argv)
{
    test_00();
    test_01();
    return ::boost::report_errors();
}

